/**
 * The dsh-overleaf bridge script. Served same-origin at
 * `/overleaf-workbench/bridge.js` and injected as an external classic script
 * right after `<head>` on every proxied HTML response (external same-origin
 * script survives strict `script-src 'self'` CSPs where inline handlers fail).
 *
 * Responsibilities:
 *  - Route every same-origin root-relative URL (fetch/XHR/EventSource/
 *    WebSocket/link/form/navigation) under the proxy prefix by combining a
 *    document-level `<base>` (written by the proxy rewrite) with defensive
 *    runtime wrappers installed here at document start.
 *  - Report text selections to the GUI shell (R5 quote pipeline source).
 *  - Insert generated text at the editor caret (R6) with a local snapshot +
 *    rollback buffer.
 *  - Scroll to & flash a quoted range when the composer chip asks (R5).
 */

/**
 * Raw browser-side script. Kept as one double-quoted-free normal TS string;
 * build copies it verbatim into the bundle.
 */
import { renderTexpageBibAdapter } from './texpage-bib.ts'
import { renderTexpageTexAdapter } from './texpage-tex.ts'

export const BRIDGE_SCRIPT_NAME = 'bridge.js'

export function renderBridgeScript(): string {
  return `/* dsh-overleaf bridge v1 (auto-generated by the plugin host; do not edit) */
;(function () {
  'use strict'
  var NS = 'dsh-overleaf'
  if (window.__DSH_OVERLEAF_BRIDGE__) return
  window.__DSH_OVERLEAF_BRIDGE__ = true
  var DEBUG = false
  function markDiagnostic(name, value) {
    try {
      if (document.documentElement) {
        document.documentElement.setAttribute('data-dsh-overleaf-' + name, String(value).slice(0, 300))
      }
    } catch (err) {}
  }
  markDiagnostic('bridge', 'ready')
  window.addEventListener('error', function (event) {
    markDiagnostic('last-error', event && event.message ? event.message : 'script-error')
  })
  window.addEventListener('unhandledrejection', function (event) {
    var reason = event && event.reason
    markDiagnostic('last-rejection', reason && reason.message ? reason.message : String(reason || 'unhandled-rejection'))
  })
  function log() {
    if (!DEBUG || !console || !console.debug) return
    Function.prototype.apply.call(console.debug, console, ['[dsh-overleaf]'].concat([].slice.call(arguments)))
  }
  function safe(fn, label) {
    return function () {
      try {
        return fn.apply(this, arguments)
      } catch (err) {
        if (DEBUG) log(label, err)
        return undefined
      }
    }
  }
  var PREFIX = '/overleaf-proxy'
  function sendToParent(message) {
    try {
      if (window.parent && window.parent !== window) {
        message.ns = NS
        window.parent.postMessage(message, '*')
      }
    } catch (err) {
      if (DEBUG) log('send failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Request routing helpers                                          */
  /* ---------------------------------------------------------------- */

  function isProxyUrl(value) {
    return typeof value === 'string' && (value.indexOf(PREFIX + '/') === 0)
  }

  /* User-content output-file origin (Overleaf serves PDFs/logs from a second
     host - compiles.overleafusercontent.com - announced in the shell meta tag
     ol-compilesUserContentDomain). The compile-result URL builder prepends
     that absolute host to output-file paths with window.origin semantics, so
     fetches escape the embedded origin and are CORS-blocked. Re-rooting them
     under the proxy lets the same-origin tunnel fetch the bytes (the locked
     main origin 404s on those paths). The meta may not be parsed yet while
     this script runs (it is injected right after <head>), so the lookup
     retries until it lands. */
  var contentOriginSeen = false
  var contentOriginValue = ''
  function readContentOrigin() {
    try {
      var metas = document.querySelectorAll('meta[name="ol-compilesUserContentDomain"], meta[name="ol-userContentDomain"]')
      for (var i = 0; i < metas.length; i++) {
        if (metas[i] && metas[i].content) return String(metas[i].content)
      }
    } catch (err) {}
    return undefined
  }
  function contentOrigin() {
    if (!contentOriginSeen) {
      var raw = readContentOrigin()
      if (raw !== undefined && raw !== '') {
        try {
          contentOriginValue = new URL(raw).origin
          markDiagnostic('content-origin', contentOriginValue)
        } catch (err) {
          contentOriginValue = ''
        }
        contentOriginSeen = true
      }
      /* else: meta not parsed yet - retry on the next request */
    }
    return contentOriginValue
  }

  function routeUrl(raw) {
    try {
      if (raw instanceof URL) raw = raw.toString()
      if (typeof raw !== 'string') return raw
      // Root-relative upstream URLs are re-rooted under the proxy.
      if (raw.charAt(0) === '/' && raw.indexOf('//') !== 0) {
        if (raw === PREFIX || raw.indexOf('/overleaf/workbench/') === 0) return raw
        if (!isProxyUrl(raw)) return PREFIX + raw
        return raw
      }
      // Overleaf's compile result builder deliberately turns output-file paths
      // into absolute URLs with window.origin + file.url. Inside the embedded
      // page, window.origin is the DSH loopback shell, so those PDF/log fetches
      // bypass the proxy unless absolute same-origin URLs are re-rooted too.
      // Relative strings are left alone so the injected <base> keeps handling
      // their root semantics; external/CDN/blob/data origins remain untouched.
      var isAbsolute = raw.indexOf('//') === 0 || /^[a-z][a-z0-9+.-]*:/i.test(raw)
      if (isAbsolute) {
        var upstreamOrigin = typeof window.__DSH_OVERLEAF_UPSTREAM_ORIGIN__ === 'string'
          ? window.__DSH_OVERLEAF_UPSTREAM_ORIGIN__ : ''
        var upstreamProtocol = upstreamOrigin ? new URL(upstreamOrigin).protocol : location.protocol
        var protocolRelative = raw.indexOf('//') === 0
        var parsed = new URL(protocolRelative ? upstreamProtocol + raw : raw)
        // blob: URLs report their creator's origin, but are not HTTP resources.
        // PDF viewers/workers must keep those object URLs intact.
        if (!/^https?:$/.test(parsed.protocol)) return raw
        // TeXPage builds API bases with location.hostname (no loopback port).
        // Only that protocol-relative, implicit-port form aliases this proxy;
        // explicit other ports/hosts remain external.
        var implicitCurrentHost = protocolRelative && parsed.hostname === window.location.hostname && parsed.port === ''
        // TeXPage returns signed PDF URLs over Socket.IO, not Overleaf compile
        // JSON/meta tags. Send only the announced fixed host's PDF/log outputs
        // through its isolated credential-free handler; preserve signed query.
        var announcedOutput = window.__DSH_OVERLEAF_TEXPAGE_OUTPUT_ORIGIN__
        if (announcedOutput === 'https://latex-file.texpageusercontent.com'
          && parsed.origin === announcedOutput && parsed.username === '' && parsed.password === ''
          && /^\\/CompileResult\\/[a-zA-Z0-9_-]+\\/[a-zA-Z0-9_-]+\\/[a-zA-Z0-9_-]+\\/output\\.(?:pdf|log|blg)$/.test(parsed.pathname)) {
          markDiagnostic(/\\.pdf$/.test(parsed.pathname) ? 'pdf-route' : 'log-route', 'texpage-same-origin')
          return window.location.origin + PREFIX + '/__dsh_texpage_output__' + parsed.pathname + parsed.search
        }
        var announcedSocket = window.__DSH_OVERLEAF_SOCKET_ORIGIN__
        if (typeof announcedSocket === 'string' && /^https?:$/.test(parsed.protocol) && parsed.host === new URL(announcedSocket).host
          && /^\\/(?:socket\\.io\\/?|heartbeat)$/.test(parsed.pathname)) {
          return window.location.origin + PREFIX + '/__dsh_socket__' + parsed.pathname + parsed.search + parsed.hash
        }
        var isWorkbenchRoute = parsed.pathname.indexOf('/overleaf/workbench/') === 0
        var isAlreadyProxied = parsed.pathname === PREFIX || parsed.pathname.indexOf(PREFIX + '/') === 0
        if ((parsed.origin === window.location.origin || parsed.origin === upstreamOrigin || implicitCurrentHost)
          && !isWorkbenchRoute && !isAlreadyProxied) {
          return window.location.origin + PREFIX + parsed.pathname + parsed.search + parsed.hash
        }
        // Absolute URLs on the site's user-content output origin are re-rooted
        // under the proxy (keeps the path - the host proxy forwards zone paths
        // to that origin after learning it from the compile result).
        var contentDom = contentOrigin()
        if (contentDom !== '' && parsed.origin === contentDom && !isWorkbenchRoute && !isAlreadyProxied) {
          return PREFIX + parsed.pathname + parsed.search + parsed.hash
        }
        if (protocolRelative) return parsed.toString()
      }
      return raw
    } catch (err) {
      return raw
    }
  }

  /* ---------------------------------------------------------------- */
  /* Compile-log capture (auto-fix source)                             */
  /*                                                                    */
  /* The panel's compile-fix tab needs the raw compiler output. Every    */
  /* compile POST and every output.pdf load passes the fetch/XHR        */
  /* wrappers below; when one is seen, the same build's output.log      */
  /* (and .blg) are fetched through the proxy and published to the      */
  /* shell. NOTE: this file is generated from a TS template literal -   */
  /* every regex backslash must be doubled, and no backtick or dollar-  */
  /* brace sequence may appear (even in comments).                      */
  /* ---------------------------------------------------------------- */
  var lastCompileStatus = undefined
  var lastCompileLogs = undefined
  var compileGeneration = 0
  var logFetchInFlight = Object.create(null)

  function pathnameOf(rawUrl) {
    try {
      if (rawUrl instanceof URL) rawUrl = rawUrl.toString()
      if (typeof rawUrl !== 'string' || rawUrl === '') return ''
      var absolute = rawUrl.indexOf('//') === 0
        ? location.protocol + rawUrl
        : (/^[a-z][a-z0-9+.-]*:/i.test(rawUrl) ? rawUrl : location.origin + (rawUrl.charAt(0) === '/' ? rawUrl : '/' + rawUrl))
      return new URL(absolute).pathname
    } catch (err) {
      return ''
    }
  }

  function isCompilePost(rawUrl) {
    var pathName = pathnameOf(rawUrl)
    if (pathName.indexOf(PREFIX + '/') === 0) pathName = pathName.slice(PREFIX.length)
    return /^\\/project\\/[^/]+\\/compile\\/?$/.test(pathName)
  }

  function isCachedCompileResponse(rawUrl) {
    var pathName = pathnameOf(rawUrl)
    if (pathName.indexOf(PREFIX + '/') === 0) pathName = pathName.slice(PREFIX.length)
    return /^\\/project\\/[^/]+\\/output\\/cached\\/output\\.overleaf\\.json$/.test(pathName)
  }

  function isOutputPdf(rawUrl) {
    return /\\/output\\/output\\.pdf(?:[?#]|$)/.test(pathnameOf(rawUrl))
  }

  function isCompileLog(rawUrl) {
    return /\\/output\\/[^/]+\\.(?:log|blg)$/i.test(pathnameOf(rawUrl))
  }

  function compileLogPath(rawUrl) {
    var pathName = pathnameOf(rawUrl)
    var name = pathName.slice(pathName.lastIndexOf('/') + 1)
    return name || 'output.log'
  }

  function truncateText(text, max) {
    if (typeof text !== 'string') return ''
    return text.length > max ? text.slice(0, max) + '\\n...[truncated]' : text
  }

  function fetchWithTimeout(url) {
    try {
      var controller = typeof AbortController === 'function' ? new AbortController() : undefined
      if (controller) setTimeout(function () { try { controller.abort() } catch (err) {} }, 30000)
      var fetchImpl = originalFetch || window.fetch
      return fetchImpl.call(window, routeUrl(url), {
        cache: 'no-store',
        signal: controller ? controller.signal : undefined,
      })
    } catch (err) {
      return Promise.reject(err)
    }
  }

  function publishCompileLog() {
    sendToParent({
      type: 'compile-log',
      status: lastCompileStatus || 'unknown',
      files: lastCompileLogs || [],
    })
  }

  function beginCompileGeneration(status) {
    compileGeneration += 1
    lastCompileStatus = status || 'compiling'
    lastCompileLogs = []
    publishCompileLog()
    return compileGeneration
  }

  function storeCompileLog(captured, generation) {
    if (generation !== compileGeneration) return
    var previous = lastCompileLogs || []
    var rest = previous.filter(function (item) { return item && item.path !== captured.path })
    lastCompileLogs = rest.concat([captured])
    markDiagnostic('compile-log', captured.path + (captured.error ? ':' + captured.error : ':' + captured.text.length))
    publishCompileLog()
  }

  function fetchAndPublishLog(fullUrl, pathName, generation) {
    var requestGeneration = typeof generation === 'number' ? generation : compileGeneration
    var flightKey = String(requestGeneration) + '|' + String(fullUrl)
    if (logFetchInFlight[flightKey]) return
    logFetchInFlight[flightKey] = true
    fetchWithTimeout(fullUrl)
      .then(function (response) {
        if (!response.ok) return { path: pathName, text: '', error: 'HTTP ' + response.status }
        return response.text().then(function (text) {
          return { path: pathName, text: truncateText(text, 1048576) }
        })
      })
      .then(function (captured) {
        storeCompileLog(captured, requestGeneration)
      })
      .catch(function (err) {
        storeCompileLog({
          path: pathName,
          text: '',
          error: err && err.message ? String(err.message) : String(err),
        }, requestGeneration)
        if (DEBUG) log('compile log fetch failed', err)
      })
      .finally(function () { delete logFetchInFlight[flightKey] })
  }

  /* Overleaf itself reads output.log to build its native error panel. Capture
     that successful response too: it is the most reliable source because it
     already contains the exact build URL and authorization query selected by
     the current frontend. */
  function captureObservedLogResponse(response, rawUrl, generation) {
    var pathName = compileLogPath(rawUrl)
    try {
      if (!response || !response.ok) {
        storeCompileLog({ path: pathName, text: '', error: 'HTTP ' + (response ? response.status : 0) }, generation)
        return
      }
      response.clone().text()
        .then(function (text) {
          storeCompileLog({ path: pathName, text: truncateText(text, 1048576) }, generation)
        })
        .catch(function (err) {
          storeCompileLog({ path: pathName, text: '', error: String(err) }, generation)
        })
    } catch (err) {
      storeCompileLog({ path: pathName, text: '', error: String(err) }, generation)
    }
  }

  /* Observed on a compile POST response: read outputFiles, fetch every
     .log/.blg through the proxy with the same compileGroup/clsiServerId
     query the frontend uses. */
  function captureCompileResponse(json, requestedGeneration) {
    try {
      if (!json || !json.outputFiles || !Array.isArray(json.outputFiles)) return
      var generation = typeof requestedGeneration === 'number'
        ? requestedGeneration
        : beginCompileGeneration(typeof json.status === 'string' ? json.status : 'unknown')
      if (generation !== compileGeneration) return
      if (typeof json.status === 'string') lastCompileStatus = json.status
      publishCompileLog()
      var pdfDomain = typeof json.pdfDownloadDomain === 'string' ? json.pdfDownloadDomain : ''
      var params = new URLSearchParams()
      if (json.compileGroup) params.set('compileGroup', String(json.compileGroup))
      if (json.clsiServerId) params.set('clsiserverid', String(json.clsiServerId))
      for (var p = 0; p < json.outputFiles.length; p++) {
        var pdfEntry = json.outputFiles[p]
        if (pdfEntry && pdfEntry.path === 'output.pdf' && pdfEntry.editorId) {
          params.set('editorId', String(pdfEntry.editorId))
          break
        }
      }
      params.set('enable_pdf_caching', 'true')
      var found = []
      for (var i = 0; i < json.outputFiles.length; i++) {
        var entry = json.outputFiles[i]
        var filePath = entry && typeof entry.path === 'string' ? entry.path : ''
        var relUrl = entry && typeof entry.url === 'string' ? entry.url : ''
        if (!/\\.(?:log|blg)$/i.test(filePath) || relUrl === '' || found.length >= 4) continue
        /* Match Overleaf's own URL builder: only entries explicitly marked as
           build artifacts use pdfDownloadDomain. output.log normally stays on
           window.origin and therefore must travel through /overleaf-proxy. */
        var target = entry && entry.build && pdfDomain !== '' && relUrl.charAt(0) === '/'
          ? pdfDomain + relUrl
          : relUrl
        var absoluteTarget = target.indexOf('//') === 0
          ? location.protocol + target
          : (/^[a-z][a-z0-9+.-]*:/i.test(target) ? target : location.origin + (target.charAt(0) === '/' ? target : '/' + target))
        var parsedTarget = new URL(absoluteTarget)
        params.forEach(function (value, key) {
          if (!parsedTarget.searchParams.has(key)) parsedTarget.searchParams.set(key, value)
        })
        found.push({ path: filePath, url: routeUrl(parsedTarget.toString()) })
      }
      for (var j = 0; j < found.length; j++) {
        fetchAndPublishLog(found[j].url, found[j].path, generation)
      }
    } catch (err) {
      if (DEBUG) log('compile capture failed', err)
    }
  }

  /* Fallback: an output.pdf load also reveals the build path - fetch the
     companion output.log with the SAME query the pdf request carried. */
  function captureLogFromOutputPdf(rawUrl) {
    try {
      var absolute = rawUrl.indexOf('//') === 0
        ? location.protocol + rawUrl
        : (/^[a-z][a-z0-9+.-]*:/i.test(rawUrl) ? rawUrl : location.origin + rawUrl)
      var parsed = new URL(absolute)
      if (!/\\.pdf$/i.test(parsed.pathname)) return
      /* /download/project/.../output.pdf is a download controller, not the
         output-file path. Replacing its extension produces a guaranteed 404. */
      if (/\\/download\\/project\\//.test(parsed.pathname)) return
      parsed.pathname = parsed.pathname.replace(/\\.pdf$/i, '.log')
      fetchAndPublishLog(parsed.toString(), 'output.log', compileGeneration)
    } catch (err) {
      if (DEBUG) log('pdf log fallback failed', err)
    }
  }

  function currentFileTreeDocument() {
    try {
      var root = document.querySelector('[data-testid="file-tree-list-root"]')
      if (!root) return undefined
      var selected = root.querySelectorAll('[role="treeitem"][aria-selected="true"][aria-label]')
      var found = []
      for (var i = 0; i < selected.length; i++) {
        var entity = selected[i].querySelector('.entity[data-file-id][data-file-type="doc"]')
        if (!entity) continue
        var name = String(selected[i].getAttribute('aria-label') || '').replace(/[\u200e\u200f]/g, '').trim()
        if (name === '') continue
        found.push({ item: selected[i], entity: entity, id: String(entity.getAttribute('data-file-id') || ''), name: name })
      }
      return found.length === 1 ? found[0] : undefined
    } catch (err) {
      return undefined
    }
  }

  function currentDocName() {
    try {
      var selected = currentFileTreeDocument()
      if (selected) return selected.name
      var candidates = document.querySelectorAll('.document-title, [class*="document-title"], [class*="doc-title"], [class*="file-tree"] [class*="name"]')
      for (var i = 0; i < candidates.length; i++) {
        if (candidates[i] && candidates[i].textContent) {
          var text = String(candidates[i].textContent).trim()
          if (text !== '' && text.length < 120) return text
        }
      }
    } catch (err) {}
    return 'current-document'
  }

  /* Apply a validated edit list (each old must match once) to the live
     editor document, from the LAST edit backwards so ranges stay valid. */
  function applyFixEdits(edits) {
    try {
      if (!Array.isArray(edits) || edits.length === 0) {
        sendToParent({ type: 'fix-applied', ok: false, error: 'no-edits' })
        return
      }
      var cm5 = findCm5()
      if (cm5) {
        var doc5 = String(cm5.getValue())
        var steps5 = buildFixSteps(edits, doc5)
        if (!steps5.ok) { sendToParent({ type: 'fix-applied', ok: false, error: steps5.error, detail: steps5.detail }); return }
        rememberSnapshot(doc5)
        var sorted5 = steps5.steps.slice().sort(function (a, b) { return b.from - a.from })
        for (var s5 = 0; s5 < sorted5.length; s5++) {
          cm5.replaceRange(sorted5[s5].replacement, cm5.posFromIndex(sorted5[s5].from), cm5.posFromIndex(sorted5[s5].to))
        }
        cm5.focus()
        sendToParent({ type: 'fix-applied', ok: true, applied: sorted5.length })
        return
      }
      var cm6 = findCm6()
      if (cm6) {
        var doc6 = cm6.state.doc.toString()
        var steps6 = buildFixSteps(edits, doc6)
        if (!steps6.ok) { sendToParent({ type: 'fix-applied', ok: false, error: steps6.error, detail: steps6.detail }); return }
        rememberSnapshot(doc6)
        var sorted6 = steps6.steps.slice().sort(function (a, b) { return b.from - a.from })
        cm6.dispatch({
          changes: sorted6.map(function (step) { return { from: step.from, to: step.to, insert: step.replacement } }),
        })
        cm6.focus()
        sendToParent({ type: 'fix-applied', ok: true, applied: sorted6.length })
        return
      }
      sendToParent({ type: 'fix-applied', ok: false, error: 'no-editor' })
    } catch (err) {
      sendToParent({ type: 'fix-applied', ok: false, error: err && err.message ? err.message : String(err) })
    }
  }

  function buildFixSteps(edits, doc) {
    var steps = []
    for (var i = 0; i < edits.length; i++) {
      var edit = edits[i]
      var oldText = edit && typeof edit.old === 'string' ? edit.old : ''
      var newText = edit && typeof edit.new === 'string' ? edit.new : ''
      if (oldText === '') return { ok: false, error: 'empty-old' }
      if (oldText.length > doc.length) return { ok: false, error: 'not-found', detail: oldText.slice(0, 80) }
      var first = doc.indexOf(oldText)
      if (first < 0) return { ok: false, error: 'not-found', detail: oldText.slice(0, 80) }
      if (doc.indexOf(oldText, first + 1) >= 0) return { ok: false, error: 'not-unique', detail: oldText.slice(0, 80) }
      steps.push({ from: first, to: first + oldText.length, replacement: newText })
    }
    return { ok: true, steps: steps }
  }

  function clickRecompile() {
    try {
      var candidates = document.querySelectorAll('button, [role="button"], [aria-label]')
      for (var i = 0; i < candidates.length; i++) {
        var el = candidates[i]
        var aria = String(el.getAttribute && el.getAttribute('aria-label') || '')
        var title = String(el.getAttribute && el.getAttribute('title') || '')
        var label = String(el.textContent || '').trim()
        if (/^(recompile|compile|重新编译|编译)$/i.test(label) || /^recompile$/i.test(aria) || /^recompile$/i.test(title)) {
          (function (target) {
            setTimeout(function () { try { target.click() } catch (err) {} }, 0)
          })(el)
          sendToParent({ type: 'recompile-clicked', ok: true })
          return
        }
      }
      sendToParent({ type: 'recompile-clicked', ok: false })
    } catch (err) {
      sendToParent({ type: 'recompile-clicked', ok: false })
    }
  }

  // Additive adapter: TeXPage uses a different file tree and CRDT lifecycle.
  // The legacy Overleaf bibliography code below remains the default.
  var texpageBib = ${renderTexpageBibAdapter()}({
    fetch: function () { return originalFetch.apply(window, arguments) },
    editor: function () { return currentEditableBibEditor() },
    report: sendToParent,
  })
  var texpageTex = ${renderTexpageTexAdapter()}({
    fetch: function () { return originalFetch.apply(window, arguments) },
    editor: function () { return currentEditableBibEditor() },
    report: sendToParent,
  })

  /* fetch wrapper */
  var originalFetch = null
  if (typeof window.fetch === 'function') {
    originalFetch = window.fetch
    window.fetch = safe(function (input, init) {
      var rawUrl = typeof input === 'string' ? input : (input instanceof URL ? input.toString() : (typeof Request === 'function' && input instanceof Request ? input.url : ''))
      var fetchMethod = String((init && init.method) || (typeof Request === 'function' && input instanceof Request ? input.method : 'GET')).toUpperCase()
      var requestGeneration = compileGeneration
      if (rawUrl !== '' && isCompilePost(rawUrl) && fetchMethod === 'POST') {
        requestGeneration = beginCompileGeneration('compiling')
      }
      if (typeof input === 'string' || input instanceof URL) {
        arguments[0] = routeUrl(input)
      } else if (typeof Request === 'function' && input instanceof Request) {
        // Some PDF loaders pre-build a Request from the absolute output URL.
        // Clone it with the routed URL so method, headers, body and signal are
        // retained while the destination moves under /overleaf-proxy.
        try {
          var routedRequestUrl = routeUrl(input.url)
          if (routedRequestUrl !== input.url) arguments[0] = new Request(routedRequestUrl, input)
        } catch (requestError) {
          if (DEBUG) log('request url fix failed', requestError)
        }
      }
      var routedResult = originalFetch.apply(window, arguments)
      if (rawUrl !== '' && pathnameOf(rawUrl).indexOf('/api/project/fileTree') !== -1) {
        routedResult.then(function (response) {
          if (!response.ok) return
          response.clone().json().then(function (json) {
            texpageBib.observe(routeUrl(rawUrl), json)
            texpageTex.observe(routeUrl(rawUrl), json)
          }).catch(function () {})
        }).catch(function () {})
      }
      // Compile-fix source: compile POST responses reveal output.log/.blg URLs;
      // an output.pdf load reveals the build path as a fallback.
      if (rawUrl !== '' && (isCompilePost(rawUrl) || isCachedCompileResponse(rawUrl))) {
        if ((isCompilePost(rawUrl) && fetchMethod === 'POST') || (isCachedCompileResponse(rawUrl) && fetchMethod === 'GET')) {
          routedResult
            .then(function (response) {
              try {
                response.clone().json()
                  .then(function (json) {
                    captureCompileResponse(json, isCompilePost(rawUrl) ? requestGeneration : undefined)
                  })
                  .catch(function () {})
              } catch (err) {
                if (DEBUG) log('compile clone failed', err)
              }
            })
            .catch(function () {})
        }
      } else if (rawUrl !== '' && isCompileLog(rawUrl)) {
        routedResult
          .then(function (response) { captureObservedLogResponse(response, rawUrl, requestGeneration) })
          .catch(function (err) {
            storeCompileLog({ path: compileLogPath(rawUrl), text: '', error: String(err) }, requestGeneration)
          })
      } else if (rawUrl !== '' && isOutputPdf(rawUrl)) {
        setTimeout(function () { captureLogFromOutputPdf(rawUrl) }, 0)
      }
      return routedResult
    }, 'fetch wrap')
  }

  /* XMLHttpRequest.open wrapper */
  try {
    var proto = window.XMLHttpRequest && window.XMLHttpRequest.prototype
    if (proto && typeof proto.open === 'function') {
      var originalOpen = proto.open
      proto.open = safe(function (method, url) {
        var rawUrl = typeof url === 'string' ? url : ''
        var xhrGeneration = compileGeneration
        if (rawUrl !== '' && isCompilePost(rawUrl) && String(method || 'GET').toUpperCase() === 'POST') {
          xhrGeneration = beginCompileGeneration('compiling')
        }
        if (typeof url === 'string') {
          arguments[1] = routeUrl(url)
        }
        if (typeof arguments[1] === 'string' && arguments[1].indexOf(PREFIX + '/__dsh_texpage_output__/') !== -1) {
          // Safe diagnostic only: never expose signed URLs, query values or
          // document bytes in the DOM/console.
          var outputStatusKey = /\\.pdf(?:[?#]|$)/.test(arguments[1]) ? 'pdf-status' : 'log-status'
          this.addEventListener('loadend', function () { markDiagnostic(outputStatusKey, this.status) })
        }
        // XHR backup for the compile-log source (some deployments/issues use
        // XHR for the compile POST - the fetch wrapper alone would miss them).
        if (rawUrl !== '' && typeof this.addEventListener === 'function') {
          try {
            var xhr = this
            xhr.addEventListener('readystatechange', function () {
              if (xhr.readyState !== 4) return
              try {
                if (xhr.status === 200 && pathnameOf(rawUrl).indexOf('/api/project/fileTree') !== -1) {
                  var treeJson = JSON.parse(xhr.responseText)
                  texpageBib.observe(routeUrl(rawUrl), treeJson)
                  texpageTex.observe(routeUrl(rawUrl), treeJson)
                }
                if ((isCompilePost(rawUrl) || isCachedCompileResponse(rawUrl)) && xhr.status === 200 && typeof xhr.responseText === 'string' && xhr.responseText !== '') {
                  var parsedPayload = JSON.parse(xhr.responseText)
                  if (parsedPayload) captureCompileResponse(parsedPayload, isCompilePost(rawUrl) ? xhrGeneration : undefined)
                } else if (isCompileLog(rawUrl)) {
                  if (xhr.status >= 200 && xhr.status < 300 && typeof xhr.responseText === 'string') {
                    storeCompileLog({ path: compileLogPath(rawUrl), text: truncateText(xhr.responseText, 1048576) }, xhrGeneration)
                  } else {
                    storeCompileLog({ path: compileLogPath(rawUrl), text: '', error: 'HTTP ' + xhr.status }, xhrGeneration)
                  }
                } else if (isOutputPdf(rawUrl)) {
                  captureLogFromOutputPdf(rawUrl)
                }
              } catch (err) {
                if (DEBUG) log('xhr compile capture failed', err)
              }
            })
          } catch (err) {
            if (DEBUG) log('xhr hook failed', err)
          }
        }
        return originalOpen.apply(this, arguments)
      }, 'xhr wrap')
    }
  } catch (err) {
    if (DEBUG) log('xhr patch skipped', err)
  }

  /* EventSource wrapper.

     MUST use class extends: EventSource is a real DOM constructor and cannot
     be invoked via .call() — the previous prototype-shuffle wrapper made
     EVERY new EventSource(...) on the page throw
     "Failed to construct 'EventSource'" and broke all SSE consumers. */
  try {
    if (typeof window.EventSource === 'function') {
      var OriginalEventSource = window.EventSource
      class PatchedEventSource extends OriginalEventSource {
        constructor(url, config) {
          if (typeof url === 'string') url = routeUrl(url)
          super(url, config)
        }
      }
      Object.defineProperty(PatchedEventSource, 'name', { value: 'EventSource' })
      window.EventSource = PatchedEventSource
    }
  } catch (err) {
    if (DEBUG) log('eventsource patch skipped', err)
  }

  /* WebSocket transport (socket.io websocket upgrade path).

     The webserver's upgrade registry is exact-path only and cannot host
     socket.io's dynamic upgrade URLs, so the plugin runs a companion tunnel
     on its own loopback port (injected as __DSH_OVERLEAF_WS_PORT__). When
     that port is known, same-origin WebSocket targets are redirected there;
     the tunnel forwards the request verbatim to the upstream origin. */
  function routeSocketUrl(raw) {
    if (typeof raw !== 'string' && !(raw instanceof URL)) return raw
    var parsed = new URL(String(raw), window.location.href)
    if (!/^(?:https?|wss?):$/.test(parsed.protocol) || parsed.username || parsed.password) return raw
    var path = parsed.pathname
    var socketOrigin = window.__DSH_OVERLEAF_SOCKET_ORIGIN__
    var upstreamOrigin = window.__DSH_OVERLEAF_UPSTREAM_ORIGIN__
    var socketHost = typeof socketOrigin === 'string' ? new URL(socketOrigin).host : ''
    var upstreamHost = typeof upstreamOrigin === 'string' ? new URL(upstreamOrigin).host : ''
    if (socketHost !== '' && parsed.host === socketHost) {
      if (!/^\\/socket\\.io\\/?$/.test(path)) return raw
      path = '/__dsh_socket__' + path
    } else if (parsed.host !== window.location.host && parsed.host !== upstreamHost) {
      return raw
    }
    var port = parseInt(window.__DSH_OVERLEAF_WS_PORT__, 10) || 0
    var protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'
    if (port > 0) return protocol + '//127.0.0.1:' + port + path + parsed.search
    if (path.indexOf(PREFIX + '/') !== 0) path = PREFIX + path
    return protocol + '//' + window.location.host + path + parsed.search
  }
  try {
    var OriginalWebSocket = window.WebSocket
    if (typeof OriginalWebSocket === 'function') {
      var WS_PORT = parseInt(window.__DSH_OVERLEAF_WS_PORT__, 10) || 0
      markDiagnostic('ws-port', WS_PORT)
      function PatchedWebSocket(url, protocols) {
        try {
          url = routeSocketUrl(url)
        } catch (err) {
          if (DEBUG) log('ws url fix failed', err)
        }
        var socketUrl = String(url)
        try {
          var parsedSocketUrl = new URL(socketUrl)
          markDiagnostic('ws-target', parsedSocketUrl.host)
        } catch (err) {
          markDiagnostic('ws-target', 'invalid-url')
        }
        markDiagnostic('ws-state', 'connecting')
        markDiagnostic('socketio-state', 'connecting')
        var messageCount = 0
        markDiagnostic('ws-messages', 0)
        var socket = new OriginalWebSocket(url, protocols)
        socket.addEventListener('open', function () { markDiagnostic('ws-state', 'open') })
        socket.addEventListener('message', function (event) {
          messageCount += 1
          markDiagnostic('ws-messages', messageCount)
          // Report protocol milestones, never payloads, session IDs or tokens.
          if (typeof event.data === 'string') {
            if (event.data.indexOf('40') === 0) markDiagnostic('socketio-state', 'connected')
            else if (event.data.indexOf('44') === 0) markDiagnostic('socketio-state', 'connect-error')
          }
        })
        socket.addEventListener('error', function () { markDiagnostic('ws-state', 'error') })
        socket.addEventListener('close', function (event) {
          markDiagnostic('ws-state', 'closed:' + String(event && event.code || 0))
          markDiagnostic('socketio-state', 'closed')
        })
        return socket
      }
      Object.defineProperty(PatchedWebSocket, 'name', { value: 'WebSocket' })
      // Preserve the native constructor contract. Overleaf compares its
      // connection state against WebSocket.OPEN/CLOSED before it ever creates
      // a socket; dropping those static constants makes both sides undefined
      // and canReconnect() stays false forever. Sharing the native prototype
      // also keeps event.target instanceof WebSocket true after wrapping.
      Object.setPrototypeOf(PatchedWebSocket, OriginalWebSocket)
      PatchedWebSocket.prototype = OriginalWebSocket.prototype
      window.WebSocket = PatchedWebSocket
    }
  } catch (err) {
    if (DEBUG) log('websocket patch skipped', err)
  }

  /* navigator.sendBeacon wrapper (analytics endpoints like /event/* are
     POSTed through it and would otherwise bypass the proxy). */
  try {
    if (navigator.sendBeacon && !navigator.sendBeacon.__dshOverleafWrapped) {
      var originalSendBeacon = navigator.sendBeacon.bind(navigator)
      var wrappedSendBeacon = function (url, data) {
        try {
          if (typeof url === 'string') url = routeUrl(url)
        } catch (err) {
          if (DEBUG) log('beacon url fix failed', err)
        }
        return originalSendBeacon(url, data)
      }
      wrappedSendBeacon.__dshOverleafWrapped = true
      Object.defineProperty(navigator, 'sendBeacon', { value: wrappedSendBeacon, configurable: true })
    }
  } catch (err) {
    if (DEBUG) log('sendBeacon patch skipped', err)
  }

  /* Resource-load failure fallback (capture phase - resource errors do not
     bubble). If an IMG/SCRIPT/LINK failed on an un-prefixed root-relative
     URL that slipped past every other rewriter, rebase it in place once and
     let the browser retry. */
  try {
    document.addEventListener('error', safe(function (event) {
      try {
        var el = event.target
        if (!el || el.nodeType !== 1 || !el.getAttribute) return
        var tag = el.tagName
        var attr = tag === 'IMG' ? 'src' : tag === 'SCRIPT' ? 'src' : tag === 'LINK' ? 'href' : null
        if (attr === null) return
        var value = el.getAttribute(attr)
        if (typeof value !== 'string' || value.charAt(0) !== '/' || value.indexOf(PREFIX) === 0
          || value.indexOf('/overleaf/workbench/') === 0) return
        if (el.getAttribute('data-dsh-retried')) return
        el.setAttribute('data-dsh-retried', '1')
        el.setAttribute(attr, PREFIX + value)
      } catch (err) {}
    }, 'resource error fallback'), true)
  } catch (err) {
    if (DEBUG) log('resource fallback skipped', err)
  }

  /* ---------------------------------------------------------------- */
  /* CodeMirror / editor probes                                       */
  /* ---------------------------------------------------------------- */

  function findCm5() {
    try {
      var holders = Array.prototype.slice.call(document.querySelectorAll('.CodeMirror'))
      var instances = []
      for (var i = 0; i < holders.length; i++) {
        var inst = holders[i].CodeMirror
        if (inst) instances.push(inst)
      }
      if (instances.length === 0) return undefined
      var focused = instances.filter(function (cm) { return cm.hasFocus && cm.hasFocus() })
      if (focused.length > 0) return focused[0]
      return instances[0]
    } catch (err) {
      return undefined
    }
  }

  /* Locate the live CodeMirror 6 EditorView. @codemirror/view stores the
     view on the .cm-editor DOM node under the key "cmView", but that field
     is a ContentView wrapper - the EditorView itself sits on its "view"
     property (and may be nested one level deeper), so unwrap before
     validating. NOTE: no backticks or dollar-brace sequences are allowed
     inside this template literal (see v0.1.10 lesson). */
  function asEditorView(candidate) {
    var hop = candidate
    for (var depth = 0; hop && depth < 4; depth++) {
      try {
        if (hop.state && hop.state.doc && typeof hop.dispatch === 'function') return hop
      } catch (err) {}
      hop = hop.view
    }
    return undefined
  }

  function findCm6() {
    try {
      var roots = document.querySelectorAll('.cm-editor')
      for (var i = 0; i < roots.length; i++) {
        var holder = roots[i]
        var direct = asEditorView(holder.cmView)
          || asEditorView(holder.editor)
          || asEditorView(holder.parentNode && holder.parentNode.__codemirrorView)
        if (direct) return direct
        var inner = holder.querySelector && holder.querySelector('.cm-scroller')
        if (inner) {
          var viaInner = asEditorView(inner.cmView)
          if (viaInner) return viaInner
        }
      }
      /* Last resort: scan own properties of editor DOM nodes for an object
         shaped like an EditorView (state.doc + dispatch). */
      var nodes = document.querySelectorAll('.cm-editor, .cm-content, .cm-scroller')
      for (var n = 0; n < nodes.length; n++) {
        var keys = Object.keys(nodes[n] || {})
        for (var k = 0; k < keys.length; k++) {
          var value = null
          try { value = nodes[n][keys[k]] } catch (err) { continue }
          var found = asEditorView(value)
          if (found) return found
        }
      }
      return undefined
    } catch (err) {
      return undefined
    }
  }

  function editorKind(cm) {
    if (!cm) return 'none'
    if (typeof cm.replaceSelection === 'function') return 'cm5'
    if (cm.state && typeof cm.dispatch === 'function') return 'cm6'
    return 'unknown'
  }

  var savedSelection = undefined
  var savedSelectionTargets = Object.create(null)
  var savedSelectionOrder = []
  var selectionSequence = 0

  /* Capture editor-native offsets, not just DOM selection text. The stable
     token lets the shell request a delayed replacement after an agent run. */
  function captureEditorSelection() {
    try {
      var cm5 = findCm5()
      if (cm5 && typeof cm5.getCursor === 'function' && typeof cm5.indexFromPos === 'function') {
        var doc5 = String(cm5.getValue())
        var anchor5 = cm5.indexFromPos(cm5.getCursor('anchor'))
        var head5 = cm5.indexFromPos(cm5.getCursor('head'))
        var from5 = Math.min(anchor5, head5)
        var to5 = Math.max(anchor5, head5)
        if (from5 !== to5) return rememberEditorSelection('cm5', cm5, from5, to5, doc5)
      }
      var cm6 = findCm6()
      if (cm6 && cm6.state && cm6.state.selection) {
        var main6 = cm6.state.selection.main
        var from6 = Math.min(main6.from, main6.to)
        var to6 = Math.max(main6.from, main6.to)
        if (from6 !== to6) return rememberEditorSelection('cm6', cm6, from6, to6, cm6.state.doc.toString())
      }
    } catch (err) {
      if (DEBUG) log('editor selection capture failed', err)
    }
    return undefined
  }

  function rememberEditorSelection(engine, editor, from, to, doc) {
    var text = doc.slice(from, to)
    if (!text.trim()) return undefined
    if (savedSelection && savedSelection.engine === engine && savedSelection.editor === editor && savedSelection.from === from
      && savedSelection.to === to && savedSelection.text === text) return savedSelection
    selectionSequence += 1
    savedSelection = {
      id: 'selection-' + Date.now() + '-' + selectionSequence,
      engine: engine,
      editor: editor,
      from: from,
      to: to,
      text: text,
      before: doc.slice(Math.max(0, from - 48), from),
      after: doc.slice(to, Math.min(doc.length, to + 48)),
    }
    savedSelectionTargets[savedSelection.id] = savedSelection
    savedSelectionOrder.push(savedSelection.id)
    while (savedSelectionOrder.length > 12) {
      var expiredId = savedSelectionOrder.shift()
      if (!savedSelection || expiredId !== savedSelection.id) delete savedSelectionTargets[expiredId]
    }
    return savedSelection
  }

  function replacementTargetStillMatches(target, doc) {
    if (doc.slice(target.from, target.to) !== target.text) return false
    var beforeStart = Math.max(0, target.from - target.before.length)
    if (doc.slice(beforeStart, target.from) !== target.before) return false
    return doc.slice(target.to, target.to + target.after.length) === target.after
  }

  function selectionEditorIsAttached(target) {
    try {
      var node = target.engine === 'cm5' && target.editor && typeof target.editor.getWrapperElement === 'function'
        ? target.editor.getWrapperElement()
        : target.editor && (target.editor.dom || target.editor.scrollDOM)
      return !!node && document.documentElement.contains(node)
    } catch (err) {
      return false
    }
  }

  function replaceSavedEditorSelection(id, replacement, force) {
    var target = savedSelectionTargets[id]
    if (!target) {
      sendToParent({ type: 'selection-replace-done', ok: false, error: 'selection-expired' })
      return
    }
    try {
      if (!force && (!savedSelection || savedSelection.id !== id)) throw new Error('selection-stale')
      if (target.engine === 'cm5') {
        var cm5 = target.editor
        var doc5 = cm5 && String(cm5.getValue())
        if (!cm5 || !selectionEditorIsAttached(target)) throw new Error('selection-stale')
        if (!force && !replacementTargetStillMatches(target, doc5)) throw new Error('selection-stale')
        var from5 = Math.min(Math.max(0, target.from), doc5.length)
        var to5 = Math.min(Math.max(from5, target.to), doc5.length)
        rememberSnapshot(doc5)
        cm5.replaceRange(replacement, cm5.posFromIndex(from5), cm5.posFromIndex(to5))
        cm5.setCursor(cm5.posFromIndex(from5 + replacement.length))
        cm5.focus()
      } else if (target.engine === 'cm6') {
        var cm6 = target.editor
        var doc6 = cm6 && cm6.state.doc.toString()
        if (!cm6 || !selectionEditorIsAttached(target)) throw new Error('selection-stale')
        if (!force && !replacementTargetStillMatches(target, doc6)) throw new Error('selection-stale')
        var from6 = Math.min(Math.max(0, target.from), doc6.length)
        var to6 = Math.min(Math.max(from6, target.to), doc6.length)
        rememberSnapshot(doc6)
        cm6.dispatch({
          changes: { from: from6, to: to6, insert: replacement },
          selection: { anchor: from6 + replacement.length },
        })
        cm6.focus()
      } else {
        throw new Error('selection-engine-unavailable')
      }
      delete savedSelectionTargets[id]
      if (savedSelection && savedSelection.id === id) savedSelection = undefined
      sendToParent({ type: 'selection-replace-done', ok: true, engine: target.engine, forced: force === true })
    } catch (err) {
      sendToParent({ type: 'selection-replace-done', ok: false, error: err && err.message })
    }
  }

  /* Replace a project bibliography from an explicitly selected local file.
     The bridge resolves the Overleaf target by basename, opens it through the
     real file tree, waits for the matching editor tab, and then performs one
     whole-document CodeMirror transaction so Overleaf's normal collaboration
     and autosave pipeline observes the change. */
  function normalizeBibName(value) {
    return String(value || '').replace(/[\u200e\u200f]/g, '').trim()
  }

  function bibFileTreeRoot() {
    return document.querySelector('[data-testid="file-tree-list-root"]')
  }

  function prepareBibFileTree(done) {
    try {
      var fileTreeTab = document.getElementById('ide-rail-tabs-tab-file-tree')
      if (fileTreeTab && fileTreeTab.getAttribute('aria-selected') !== 'true') fileTreeTab.click()
    } catch (err) {}
    setTimeout(function () { expandBibFolders(0, done) }, 80)
  }

  function expandBibFolders(round, done) {
    var root = bibFileTreeRoot()
    if (!root) {
      if (round >= 20) { done(); return }
      setTimeout(function () { expandBibFolders(round + 1, done) }, 100)
      return
    }
    var collapsed = root.querySelectorAll('[role="treeitem"][aria-expanded="false"]')
    var clicked = 0
    for (var i = 0; i < collapsed.length; i++) {
      var button = collapsed[i].querySelector('.file-tree-entity-button')
      if (button) { button.click(); clicked += 1 }
    }
    if (clicked > 0 && round < 8) {
      setTimeout(function () { expandBibFolders(round + 1, done) }, 100)
      return
    }
    done()
  }

  function bibTreeCandidates() {
    var root = bibFileTreeRoot()
    if (!root) return []
    var items = root.querySelectorAll('[role="treeitem"][aria-label]')
    var found = []
    for (var i = 0; i < items.length; i++) {
      var name = normalizeBibName(items[i].getAttribute('aria-label'))
      if (!/\\.bib$/i.test(name)) continue
      var entity = items[i].querySelector('.entity[data-file-id][data-file-type="doc"]')
      if (!entity) continue
      found.push({ item: items[i], entity: entity, id: String(entity.getAttribute('data-file-id') || ''), name: name })
    }
    return found
  }

  function overleafOpenDocState(id) {
    try {
      var unstable = window.overleaf && window.overleaf.unstable
      var store = unstable && unstable.store
      if (!store || typeof store.get !== 'function') return 'unavailable'
      return String(store.get('editor.open_doc_id') || '') === id ? 'match' : 'mismatch'
    } catch (err) {
      return 'unavailable'
    }
  }

  function bibTreeTargetIsSelected(target) {
    try { return target.item && target.item.getAttribute('aria-selected') === 'true' }
    catch (err) { return false }
  }

  function cleanupBibOpenListener(target) {
    if (target && typeof target.cleanupOpened === 'function') {
      target.cleanupOpened()
      target.cleanupOpened = undefined
    }
  }

  function elementIsUsable(element) {
    try {
      if (!element || !document.documentElement.contains(element)) return false
      var style = window.getComputedStyle ? window.getComputedStyle(element) : undefined
      if (style && (style.display === 'none' || style.visibility === 'hidden')) return false
      return !element.getClientRects || element.getClientRects().length > 0
    } catch (err) {
      return false
    }
  }

  function editableCm5Candidates() {
    var found = []
    try {
      var holders = document.querySelectorAll('.CodeMirror')
      for (var i = 0; i < holders.length; i++) {
        var cm = holders[i].CodeMirror
        if (!cm || !elementIsUsable(holders[i])) continue
        try { if (cm.getOption && cm.getOption('readOnly')) continue } catch (err) {}
        if (found.indexOf(cm) < 0) found.push(cm)
      }
    } catch (err) {}
    return found
  }

  function editableCm6Candidates() {
    var found = []
    try {
      var storedView = undefined
      try {
        var unstable = window.overleaf && window.overleaf.unstable
        var store = unstable && unstable.store
        storedView = asEditorView(store && typeof store.get === 'function' ? store.get('editor.view') : undefined)
      } catch (err) {}
      var roots = document.querySelectorAll('.cm-editor')
      for (var i = 0; i < roots.length; i++) {
        var holder = roots[i]
        var content = holder.querySelector('.cm-content[contenteditable="true"]')
        if (!content || !elementIsUsable(holder) || !elementIsUsable(content)) continue
        if (String(content.getAttribute('aria-label') || '').toLowerCase() === 'visual preview') continue
        /* Current Overleaf/CodeMirror 6 stores a ContentView on the live
           .cm-content node. Its root view points at the EditorView. Older
           builds used .cm-editor/.cm-scroller expandos, so retain all paths. */
        var storedDom = storedView && (storedView.dom || storedView.contentDOM)
        var storedBelongsHere = storedDom && (storedDom === holder || holder.contains(storedDom) || storedDom === content)
        if (storedBelongsHere) return [storedView]
        var view = undefined
        view = view || asEditorView(content.cmView)
          || asEditorView(content.cmView && content.cmView.rootView)
          || asEditorView(holder.cmView)
          || asEditorView(holder.editor)
          || asEditorView(holder.parentNode && holder.parentNode.__codemirrorView)
        var inner = holder.querySelector('.cm-scroller')
        if (!view && inner) view = asEditorView(inner.cmView)
        /* Some optimized builds hide the expando on a descendant other than
           the root content node. Limit the fallback scan to this visible,
           editable editor so a Visual Preview can never win. */
        if (!view) {
          var nodes = holder.querySelectorAll('.cm-content, .cm-scroller')
          for (var n = 0; n < nodes.length && !view; n++) {
            var keys = Object.keys(nodes[n] || {})
            for (var k = 0; k < keys.length; k++) {
              var value = null
              try { value = nodes[n][keys[k]] } catch (err) { continue }
              view = asEditorView(value)
              if (view) break
              try { view = asEditorView(value && value.rootView) } catch (err2) {}
              if (view) break
            }
          }
        }
        if (view && found.indexOf(view) < 0) found.push(view)
      }
    } catch (err) {}
    return found
  }

  function currentEditableBibEditor() {
    var cm5 = editableCm5Candidates()
    var cm6 = editableCm6Candidates()
    if (cm5.length + cm6.length !== 1) return { error: cm5.length + cm6.length === 0 ? 'bib-editor-unavailable' : 'bib-editor-ambiguous' }
    return cm5.length === 1 ? { engine: 'cm5', editor: cm5[0] } : { engine: 'cm6', editor: cm6[0] }
  }

  function bibEventDocId(event) {
    try {
      var detail = event && event.detail
      return String((detail && (detail.id || detail.docId || detail.doc_id)) || '')
    } catch (err) {
      return ''
    }
  }

  function listenForBibEvent(type, docId, done) {
    var finished = false
    var handler = function (event) {
      if (bibEventDocId(event) !== docId) return
      cleanup()
      done()
    }
    function cleanup() {
      if (finished) return
      finished = true
      window.removeEventListener(type, handler)
      document.removeEventListener(type, handler)
    }
    window.addEventListener(type, handler)
    document.addEventListener(type, handler)
    return cleanup
  }

  function rememberBibSnapshot(target, engine, docValue) {
    try {
      var projectMatch = /\\/project\\/([^/?#]+)/.exec(location.pathname)
      var projectId = projectMatch ? projectMatch[1] : 'unknown-project'
      var key = 'dsh-overleaf:bib-snapshot:' + projectId + ':' + target.id
      var value = JSON.stringify({
        time: Date.now(), projectId: projectId, docId: target.id,
        path: target.name, engine: engine, doc: docValue,
      })
      window.localStorage.setItem(key, value)
      if (window.localStorage.getItem(key) !== value) throw new Error('snapshot verification failed')
      sendToParent({ type: 'snapshot-saved' })
      return true
    } catch (err) {
      if (DEBUG) log('bibliography snapshot failed', err)
      return false
    }
  }

  function waitForBibSave(target, content, cleanupSaveListener, savedState, attempt) {
    if (savedState.done) {
      cleanupSaveListener()
      sendToParent({ type: 'bib-sync-done', ok: true, target: target.name, chars: content.length })
      return
    }
    if (attempt >= 120) {
      cleanupSaveListener()
      sendToParent({ type: 'bib-sync-done', ok: false, error: 'bib-save-timeout', target: target.name })
      return
    }
    setTimeout(function () { waitForBibSave(target, content, cleanupSaveListener, savedState, attempt + 1) }, 100)
  }

  function applyBibToSelectedEditor(target, content) {
    var cleanupSaveListener
    try {
      var openState = overleafOpenDocState(target.id)
      var identityReady = openState === 'match'
        || (openState === 'unavailable' && (target.opened || target.initiallySelected) && bibTreeTargetIsSelected(target))
      if (!identityReady) {
        if (Date.now() >= target.openDeadline) throw new Error('bib-editor-timeout')
        setTimeout(function () { applyBibToSelectedEditor(target, content) }, 100)
        return
      }
      cleanupBibOpenListener(target)
      if (!target.editorDeadline) target.editorDeadline = Date.now() + 8000
      var selected = currentEditableBibEditor()
      if (selected.error) {
        if (Date.now() >= target.editorDeadline) throw new Error(selected.error)
        setTimeout(function () { applyBibToSelectedEditor(target, content) }, 100)
        return
      }
      var savedState = { done: false }
      cleanupSaveListener = listenForBibEvent('doc:saved', target.id, function () { savedState.done = true })
      if (selected.engine === 'cm5') {
        var cm5 = selected.editor
        var old5 = String(cm5.getValue())
        if (old5 === content) {
          cleanupSaveListener()
          sendToParent({ type: 'bib-sync-done', ok: true, target: target.name, chars: content.length, unchanged: true })
          return
        }
        if (!rememberBibSnapshot(target, 'cm5', old5)) throw new Error('bib-snapshot-failed')
        if (typeof cm5.operation === 'function') {
          cm5.operation(function () { cm5.replaceRange(content, cm5.posFromIndex(0), cm5.posFromIndex(old5.length)) })
        } else {
          cm5.replaceRange(content, cm5.posFromIndex(0), cm5.posFromIndex(old5.length))
        }
        if (String(cm5.getValue()) !== content) throw new Error('bib-write-verification-failed')
        cm5.setCursor(cm5.posFromIndex(content.length))
        cm5.focus()
        waitForBibSave(target, content, cleanupSaveListener, savedState, 0)
        return
      }
      if (selected.engine === 'cm6') {
        var cm6 = selected.editor
        var old6 = cm6.state.doc.toString()
        if (old6 === content) {
          cleanupSaveListener()
          sendToParent({ type: 'bib-sync-done', ok: true, target: target.name, chars: content.length, unchanged: true })
          return
        }
        if (!rememberBibSnapshot(target, 'cm6', old6)) throw new Error('bib-snapshot-failed')
        cm6.dispatch({
          changes: { from: 0, to: old6.length, insert: content },
          selection: { anchor: content.length },
        })
        if (cm6.state.doc.toString() !== content) throw new Error('bib-write-verification-failed')
        cm6.focus()
        waitForBibSave(target, content, cleanupSaveListener, savedState, 0)
        return
      }
    } catch (err) {
      cleanupBibOpenListener(target)
      if (typeof cleanupSaveListener === 'function') cleanupSaveListener()
      sendToParent({ type: 'bib-sync-done', ok: false, error: err && err.message ? err.message : String(err) })
    }
  }

  function syncBibFile(fileName, content) {
    if (typeof texpageBib !== 'undefined' && texpageBib.enabled()) {
      texpageBib.sync(fileName, content)
      return
    }
    var requested = normalizeBibName(fileName)
    if (!/\\.bib$/i.test(requested)) {
      sendToParent({ type: 'bib-sync-done', ok: false, error: 'bib-invalid-name' })
      return
    }
    prepareBibFileTree(function () {
      try {
        var all = bibTreeCandidates()
        var exact = all.filter(function (candidate) { return candidate.name === requested })
        var insensitive = all.filter(function (candidate) { return candidate.name.toLowerCase() === requested.toLowerCase() })
        var matches = exact.length > 0 ? exact : insensitive
        var target = matches.length === 1 ? matches[0] : undefined
        if (!target) {
          var names = all.map(function (candidate) { return candidate.name }).join(', ')
          var reason = matches.length > 1 ? 'bib-target-ambiguous' : 'bib-target-missing'
          sendToParent({ type: 'bib-sync-done', ok: false, error: reason, available: names })
          return
        }
        target.initiallySelected = bibTreeTargetIsSelected(target)
        target.opened = false
        target.openDeadline = Date.now() + 10000
        target.editorDeadline = 0
        target.cleanupOpened = listenForBibEvent('doc:after-opened', target.id, function () {
          target.opened = true
          cleanupBibOpenListener(target)
        })
        if (!target.initiallySelected) target.entity.click()
        applyBibToSelectedEditor(target, String(content || ''))
      } catch (err) {
        cleanupBibOpenListener(typeof target === 'undefined' ? undefined : target)
        sendToParent({ type: 'bib-sync-done', ok: false, error: err && err.message ? err.message : String(err) })
      }
    })
  }

  /* Bidirectional current .tex synchronization. Overleaf-to-local reads the
     single visible source editor. Local-to-Overleaf is deliberately stricter:
     it requires an explicit confirmation bit, a stable current document id,
     a pre-change snapshot, write verification, and doc:saved confirmation. */
  function utf8TextSize(value) {
    try { return new TextEncoder().encode(String(value || '')).length }
    catch (err) { return String(value || '').length }
  }

  function texRevision(value) {
    var text = String(value || '')
    var hash = 2166136261
    for (var i = 0; i < text.length; i++) {
      hash ^= text.charCodeAt(i)
      hash = Math.imul(hash, 16777619)
    }
    return text.length + '-' + (hash >>> 0).toString(16)
  }

  function currentTexIdentity() {
    var selected = currentFileTreeDocument()
    if (!selected) throw new Error('tex-document-identity-unavailable')
    var storeId = ''
    try {
      var unstable = window.overleaf && window.overleaf.unstable
      var store = unstable && unstable.store
      if (store && typeof store.get === 'function') storeId = String(store.get('editor.open_doc_id') || '')
    } catch (err) {}
    if (storeId !== '' && selected.id !== storeId) throw new Error('tex-document-identity-mismatch')
    if (!/\.tex$/i.test(selected.name)) throw new Error('tex-current-document-not-tex')
    if (selected.id === '') throw new Error('tex-document-id-unavailable')
    return { id: selected.id, name: selected.name, selected: selected }
  }

  function currentTexEditorValue() {
    var selected = currentEditableBibEditor()
    if (selected.error) throw new Error(selected.error.replace(/^bib-/, 'tex-'))
    if (selected.engine === 'cm5') return { engine: 'cm5', editor: selected.editor, text: String(selected.editor.getValue()) }
    if (selected.engine === 'cm6') return { engine: 'cm6', editor: selected.editor, text: selected.editor.state.doc.toString() }
    throw new Error('tex-editor-unavailable')
  }

  function emitCurrentTexDocument(requestId) {
    if (typeof texpageTex !== 'undefined' && texpageTex.enabled()) {
      texpageTex.emit(requestId)
      return
    }
    try {
      var identity = currentTexIdentity()
      var current = currentTexEditorValue()
      if (utf8TextSize(current.text) > 4 * 1024 * 1024) throw new Error('tex-document-too-large')
      sendToParent({ type: 'tex-document', requestId: requestId, ok: true, id: identity.id, name: identity.name, text: current.text, revision: texRevision(current.text) })
    } catch (err) {
      sendToParent({ type: 'tex-document', requestId: requestId, ok: false, error: err && err.message ? err.message : String(err) })
    }
  }

  function rememberTexSnapshot(identity, engine, docValue) {
    try {
      var projectMatch = /\\/project\\/([^/?#]+)/.exec(location.pathname)
      var projectId = projectMatch ? projectMatch[1] : 'unknown-project'
      var key = 'dsh-overleaf:tex-snapshot:' + projectId + ':' + identity.id
      var value = JSON.stringify({
        time: Date.now(), projectId: projectId, docId: identity.id,
        path: identity.name, engine: engine, doc: docValue,
      })
      window.localStorage.setItem(key, value)
      if (window.localStorage.getItem(key) !== value) throw new Error('snapshot verification failed')
      sendToParent({ type: 'snapshot-saved' })
      return true
    } catch (err) {
      if (DEBUG) log('tex snapshot failed', err)
      return false
    }
  }

  var texSyncBusyRequestId = ''

  function waitForTexSave(identity, content, requestId, cleanupSaveListener, savedState, attempt) {
    if (savedState.done) {
      cleanupSaveListener()
      texSyncBusyRequestId = ''
      sendToParent({ type: 'tex-overleaf-sync-done', requestId: requestId, ok: true, target: identity.name, chars: content.length })
      return
    }
    if (attempt >= 120) {
      cleanupSaveListener()
      texSyncBusyRequestId = ''
      sendToParent({ type: 'tex-overleaf-sync-done', requestId: requestId, ok: false, error: 'tex-save-timeout', target: identity.name })
      return
    }
    setTimeout(function () { waitForTexSave(identity, content, requestId, cleanupSaveListener, savedState, attempt + 1) }, 100)
  }

  function syncTexToOverleaf(content, confirmed, requestId, expectedDocId, expectedRevision) {
    if (typeof texpageTex !== 'undefined' && texpageTex.enabled()) {
      texpageTex.sync(content, confirmed, requestId, expectedDocId, expectedRevision)
      return
    }
    var cleanupSaveListener
    try {
      if (texSyncBusyRequestId !== '') throw new Error('tex-sync-busy')
      texSyncBusyRequestId = requestId || 'unknown-request'
      if (confirmed !== true) throw new Error('tex-reverse-confirmation-required')
      var text = String(content || '')
      if (utf8TextSize(text) > 4 * 1024 * 1024) throw new Error('tex-document-too-large')
      var identity = currentTexIdentity()
      var current = currentTexEditorValue()
      if (String(expectedDocId || '') !== identity.id || String(expectedRevision || '') !== texRevision(current.text)) {
        throw new Error('tex-remote-changed')
      }
      if (current.text === text) {
        texSyncBusyRequestId = ''
        sendToParent({ type: 'tex-overleaf-sync-done', requestId: requestId, ok: true, target: identity.name, chars: text.length, unchanged: true })
        return
      }
      if (!rememberTexSnapshot(identity, current.engine, current.text)) throw new Error('tex-snapshot-failed')
      var savedState = { done: false }
      cleanupSaveListener = listenForBibEvent('doc:saved', identity.id, function () { savedState.done = true })
      if (current.engine === 'cm5') {
        var cm5 = current.editor
        if (typeof cm5.operation === 'function') {
          cm5.operation(function () { cm5.replaceRange(text, cm5.posFromIndex(0), cm5.posFromIndex(current.text.length)) })
        } else {
          cm5.replaceRange(text, cm5.posFromIndex(0), cm5.posFromIndex(current.text.length))
        }
        if (String(cm5.getValue()) !== text) throw new Error('tex-write-verification-failed')
        cm5.setCursor(cm5.posFromIndex(text.length))
        cm5.focus()
      } else if (current.engine === 'cm6') {
        var cm6 = current.editor
        cm6.dispatch({
          changes: { from: 0, to: current.text.length, insert: text },
          selection: { anchor: text.length },
        })
        if (cm6.state.doc.toString() !== text) throw new Error('tex-write-verification-failed')
        cm6.focus()
      }
      waitForTexSave(identity, text, requestId, cleanupSaveListener, savedState, 0)
    } catch (err) {
      if (typeof cleanupSaveListener === 'function') cleanupSaveListener()
      texSyncBusyRequestId = ''
      sendToParent({ type: 'tex-overleaf-sync-done', requestId: requestId, ok: false, error: err && err.message ? err.message : String(err) })
    }
  }

  function insertViaCm5(cm, text) {
    var snapshot = String(cm.getValue())
    rememberSnapshot(snapshot)
    cm.replaceSelection(text)
    cm.focus()
    return true
  }

  function insertViaCm6(view, text) {
    var state = view.state
    var snapshot = state.doc.toString()
    rememberSnapshot(snapshot)
    var from = state.selection.main.from
    var to = state.selection.main.to
    view.dispatch({ changes: { from: from, to: to, insert: text }, selection: { anchor: from + text.length } })
    view.focus()
    return true
  }

  function insertFallback(text) {
    var active = document.activeElement
    var editable = active && (active.tagName === 'TEXTAREA' || active.isContentEditable)
    if (editable && document.execCommand) {
      document.execCommand('insertText', false, text)
      return true
    }
    var holder = document.querySelector('.ace_text-input')
    if (holder) {
      holder.focus()
      if (document.execCommand) {
        document.execCommand('insertText', false, text)
        return true
      }
    }
    return false
  }

  /* ---------------------------------------------------------------- */
  /* Snapshot buffer (rollback)                                       */
  /* ---------------------------------------------------------------- */

  var SNAPSHOT_KEY = 'dsh-overleaf:snapshot'
  function readDocValue() {
    try {
      var cm5 = findCm5()
      if (cm5) return String(cm5.getValue())
      var cm6 = findCm6()
      if (cm6) return cm6.state.doc.toString()
      return undefined
    } catch (err) {
      return undefined
    }
  }

  /* Cursor context for AI prompts: the text around the caret plus the caret
     offset, so the agent can ground its edit in the real document. */
  function readCursorContext(radius) {
    try {
      var docValue = readDocValue()
      if (docValue === undefined) return undefined
      var text = String(docValue)
      var cursor = -1
      var cm5 = findCm5()
      if (cm5) {
        try { cursor = cm5.indexFromPos(cm5.getCursor()) } catch (err) { cursor = -1 }
      } else {
        var cm6 = findCm6()
        if (cm6) {
          try { cursor = cm6.state.selection.main.head } catch (err2) { cursor = -1 }
        }
      }
      if (cursor < 0) cursor = 0
      var r = Number(radius) || 1200
      var from = Math.max(0, cursor - r)
      var to = Math.min(text.length, cursor + r)
      return {
        cursor: cursor,
        docLength: text.length,
        before: text.slice(from, cursor),
        after: text.slice(cursor, to),
      }
    } catch (err) {
      return undefined
    }
  }
  function rememberSnapshot(docValue) {
    try {
      if (docValue === undefined || docValue === null) return
      window.localStorage.setItem(SNAPSHOT_KEY, JSON.stringify({
        time: Date.now(),
        doc: docValue,
      }))
      sendToParent({ type: 'snapshot-saved' })
    } catch (err) {
      if (DEBUG) log('snapshot failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Parent command handling                                          */
  /* ---------------------------------------------------------------- */

  window.addEventListener('message', safe(function (event) {
    if (event.source !== window.parent) return
    var data = event.data
    if (!data || data.ns !== NS) return
    if (data.type === 'insert') {
      try {
        var cm5 = findCm5()
        if (cm5) {
          insertViaCm5(cm5, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm5' })
          return
        }
        var cm6 = findCm6()
        if (cm6) {
          insertViaCm6(cm6, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm6' })
          return
        }
        var fellBack = insertFallback(String(data.text || ''))
        sendToParent({ type: 'insert-done', ok: !!fellBack, engine: fellBack ? 'fallback' : 'none',
          error: fellBack ? undefined : 'editor API not detected; paste manually from the reply' })
      } catch (err) {
        sendToParent({ type: 'insert-done', ok: false, error: err && err.message })
      }
      return
    }
    if (data.type === 'snapshot') {
      rememberSnapshot(readDocValue())
      return
    }
    if (data.type === 'selection-request') {
      emitSelection(true)
      return
    }
    if (data.type === 'replace-selection') {
      replaceSavedEditorSelection(String(data.selectionId || ''), String(data.text || ''), data.force === true)
      return
    }
    if (data.type === 'sync-bib') {
      syncBibFile(String(data.fileName || ''), String(data.text || ''))
      return
    }
    if (data.type === 'tex-document-request') {
      emitCurrentTexDocument(String(data.requestId || ''))
      return
    }
    if (data.type === 'sync-tex-to-overleaf') {
      syncTexToOverleaf(String(data.text || ''), data.confirmed === true, String(data.requestId || ''), String(data.expectedDocId || ''), String(data.expectedRevision || ''))
      return
    }
    if (data.type === 'compile-log-request') {
      publishCompileLog()
      return
    }
    if (data.type === 'document-request') {
      try {
        var docText = readDocValue()
        if (docText === undefined) {
          sendToParent({ type: 'document', name: 'current-document', text: '', error: 'no-editor' })
          return
        }
        var fullDoc = String(docText)
        var cappedDoc = truncateText(fullDoc, 200000)
        sendToParent({
          type: 'document',
          name: currentDocName(),
          text: cappedDoc,
          truncated: cappedDoc.length < fullDoc.length,
        })
      } catch (err) {
        sendToParent({ type: 'document', name: 'current-document', text: '', error: err && err.message })
      }
      return
    }
    if (data.type === 'apply-fix-edits') {
      applyFixEdits(data.edits)
      return
    }
    if (data.type === 'recompile-click') {
      clickRecompile()
      return
    }
    if (data.type === 'reveal') {
      revealText(String(data.query || ''), Number.isFinite(Number(data.line)) ? Number(data.line) : undefined)
      return
    }
    if (data.type === 'outline-request') {
      sendOutline()
      return
    }
    if (data.type === 'cursor-context-request') {
      try {
        var cc = readCursorContext(data.radius)
        if (cc === undefined) {
          sendToParent({ type: 'cursor-context', error: 'no-editor' })
        } else {
          sendToParent({ type: 'cursor-context', cursor: cc.cursor, docLength: cc.docLength, before: cc.before, after: cc.after })
        }
      } catch (err) {
        sendToParent({ type: 'cursor-context', error: err && err.message })
      }
      return
    }
    if (data.type === 'debug') {
      DEBUG = true
      return
    }
  }, 'message handler'), false)

  /* Extract a LaTeX section/subsection outline from the live editor document. */
  function sendOutline() {
    try {
      var docValue = readDocValue()
      var cm5 = findCm5()
      var cm6 = cm5 ? undefined : findCm6()
      var engine = cm5 ? 'cm5' : (cm6 ? 'cm6' : 'none')
      var debug = { engine: engine, url: location.href }
      if (docValue === undefined) {
        sendToParent({ type: 'outline', items: [], error: 'no-editor', debug: debug })
        return
      }
      /* NOTE: inside this TS template literal every backslash that must
         survive into the generated JS is doubled (\\n, \\s, \\{). A single
         \n here becomes a REAL newline in the served script and breaks it. */
      var lines = String(docValue).split('\\n')
      var items = []
      /* Starred (unnumbered) sections are outline entries too. */
      var pattern = /^\\\\(part|chapter|section|subsection|subsubsection)\\*?\\s*\\{([^}]*)}/
      for (var i = 0; i < lines.length; i++) {
        var match = pattern.exec(lines[i])
        if (!match) continue
        items.push({
          level: match[1],
          title: match[2].trim(),
          line: i,
          text: lines[i],
        })
        if (items.length >= 300) break
      }
      debug.chars = String(docValue).length
      debug.hits = items.length
      sendToParent({ type: 'outline', items: items, debug: debug })
    } catch (err) {
      sendToParent({ type: 'outline', items: [], error: err && err.message })
    }
  }

  /* Report whether the caret insertion works right now (toolbar health). */
  function reportCapabilities() {
    var kind = 'none'
    if (findCm5()) kind = 'cm5'
    else if (findCm6()) kind = 'cm6'
    sendToParent({ type: 'capabilities', editor: kind })
  }
  setTimeout(safe(reportCapabilities, 'cap probe'), 1200)

  /* ---------------------------------------------------------------- */
  /* Selection reporting (R5 source side)                             */
  /* ---------------------------------------------------------------- */

  var lastSelectionSentAt = 0
  function emitSelection(force) {
    try {
      var editorSelection = captureEditorSelection()
      if (editorSelection) {
        var editorNow = Date.now()
        if (!force && editorNow - lastSelectionSentAt < 80) return
        lastSelectionSentAt = editorNow
        sendToParent({
          type: 'selection',
          text: editorSelection.text,
          selectionId: editorSelection.id,
          engine: editorSelection.engine,
          rect: { left: 0, top: 0, right: 0, bottom: 0 },
        })
        return
      }
      /* The active editor selection was cleared or moved away. Keep its
         bounded history entry for explicit force mode, but make safe mode
         reject it as no longer current. */
      savedSelection = undefined
      var sel = window.getSelection()
      if (!sel || sel.rangeCount === 0 || sel.isCollapsed) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var text = sel.toString()
      if (!text.trim()) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var now = Date.now()
      if (!force && now - lastSelectionSentAt < 80) return
      lastSelectionSentAt = now
      var range = sel.getRangeAt(0)
      var rect = { left: 0, top: 0, right: 0, bottom: 0 }
      try {
        var box = range.getBoundingClientRect()
        rect = { left: box.left, top: box.top, right: box.right, bottom: box.bottom }
      } catch (ignoredRectError) {}
      sendToParent({ type: 'selection', text: text, engine: 'dom', rect: rect })
    } catch (err) {
      if (DEBUG) log('selection emit failed', err)
    }
  }
  document.addEventListener('selectionchange', safe(function () { emitSelection(false) }, 'selectionchange'), true)
  document.addEventListener('keyup', safe(function () { emitSelection(false) }, 'keyup-selection'), true)

  /* ---------------------------------------------------------------- */
  /* Reveal + flash (chip jump-back target)                           */
  /* ---------------------------------------------------------------- */

  function revealText(query, lineNumber) {
    try {
      if (!query && lineNumber === undefined) return
      var needle = query ? query.replace(/^\\n+|\\n+$/g, '').slice(0, 200) : ''
      var cm5 = findCm5()
      if (cm5) {
        var doc = String(cm5.getValue())
        var index = -1
        if (lineNumber !== undefined && cm5.getLineHandle) {
          var lineText = cm5.getLine(lineNumber)
          /* Line numbers in the outline are 0-based; CM5 getLine expects the
             same 0-based index, so the match must be exact. Double-check the
             text still corresponds, then fall through to string search. */
          if (lineText && needle.indexOf(lineText) !== -1) {
            try { index = cm5.indexFromPos({ line: lineNumber, ch: 0 }) } catch (err) { index = -1 }
          }
        }
        if (index < 0 && needle) index = doc.indexOf(needle)
        if (index >= 0) {
          var from = cm5.posFromIndex(index)
          var to = cm5.posFromIndex(index + Math.max(1, Math.min(needle.length || lineText.length || 1, 400)))
          cm5.setSelection(from, to)
          cm5.scrollIntoView({ from: from, to: to }, 160)
          cm5.focus()
          return
        }
      }
      /* CM6: the editor text lives in a virtualized CodeMirror document, so
         the raw line is not reachable through a DOM text-node walker. Locate
         it in state.doc (by line number first, then string), move the cursor
         there, then scroll the scroller. */
      var cm6 = findCm6()
      if (cm6) {
        var doc6 = cm6.state.doc.toString()
        var index6 = -1
        if (lineNumber !== undefined && cm6.state.doc && typeof cm6.state.doc.line === 'function') {
          try {
            var line6 = cm6.state.doc.line(lineNumber)
            if (line6 && line6.from !== undefined) index6 = line6.from
          } catch (err) { index6 = -1 }
        }
        if (index6 < 0 && needle) index6 = doc6.indexOf(needle)
        if (index6 >= 0) {
          var len = Math.max(1, Math.min(needle.length || 1, 400))
          cm6.dispatch({ selection: { anchor: index6, head: index6 + len } })
          cm6.focus()
          var scroller = cm6.dom && cm6.dom.closest ? cm6.dom.closest('.cm-scroller') : null
          var anchor = scroller || (cm6.dom || null)
          if (anchor && typeof anchor.scrollIntoView === 'function') {
            anchor.scrollIntoView({ block: 'center', behavior: 'smooth' })
          }
          return
        }
      }
      /* DOM-wide soft match otherwise */
      if (!needle) return
      var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false)
      while (walker.nextNode()) {
        var node = walker.currentNode
        if (node.nodeValue && node.nodeValue.indexOf(needle.slice(0, 60)) !== -1) {
          var parentEl = node.parentElement
          if (parentEl) {
            parentEl.scrollIntoView({ block: 'center', behavior: 'smooth' })
            var previousShadow = parentEl.style.boxShadow
            parentEl.style.boxShadow = '0 0 0 3px rgba(64,156,255,0.65)'
            setTimeout(function () { parentEl.style.boxShadow = previousShadow }, 1600)
            return
          }
        }
      }
    } catch (err) {
      if (DEBUG) log('reveal failed', err)
    }
  }

  /* Notify the shell whenever the embedded URL changes (toolbar breadcrumb). */
  function announceLocation() {
    sendToParent({ type: 'url-change', href: window.location.href })
  }
  announceLocation()
  window.addEventListener('popstate', safe(announceLocation, 'popstate'))

  /* ---------------------------------------------------------------- */
  /* Dynamic resource routing                                         */
  /*                                                                  */
  /* The proxy rewrites the INITIAL HTML server-side, but SPAs (TeXPage */
  /* dashboards, Overleaf loaders) insert scripts/styles/images at     */
  /* runtime with root-relative URLs; those would fall out of the      */
  /* proxy and hit the GUI shell's own fallback routes. Sweep existing */
  /* nodes once the DOM is ready, then watch every insertion/attribute */
  /* change and rebase matching URLs in place.                         */
  /* ---------------------------------------------------------------- */

  var RESOURCE_ATTRS = ['src', 'href', 'poster', 'data-src']
  function fixResourceNode(el) {
    try {
      if (!el || el.nodeType !== 1 || !el.hasAttribute) return
      for (var i = 0; i < RESOURCE_ATTRS.length; i++) {
        var attr = RESOURCE_ATTRS[i]
        if (!el.hasAttribute(attr)) continue
        var value = el.getAttribute(attr)
        if (typeof value !== 'string') continue
        if (value.indexOf('/overleaf/workbench/') === 0) continue
        var routed = routeUrl(value)
        if (routed !== value) el.setAttribute(attr, routed)
      }
    } catch (err) {
      if (DEBUG) log('fixResourceNode failed', err)
    }
  }
  try {
    var resourceObserver = new MutationObserver(function (mutations) {
      for (var i = 0; i < mutations.length; i++) {
        var mutation = mutations[i]
        if (mutation.type === 'attributes') {
          fixResourceNode(mutation.target)
          continue
        }
        for (var j = 0; j < mutation.addedNodes.length; j++) {
          var added = mutation.addedNodes[j]
          fixResourceNode(added)
          if (added && added.querySelectorAll) {
            var list = added.querySelectorAll('[src],[href],[poster],[data-src]')
            for (var k = 0; k < list.length; k++) fixResourceNode(list[k])
          }
        }
      }
    })
    function startResourceObserver() {
      if (!document.documentElement) {
        setTimeout(startResourceObserver, 50)
        return
      }
      resourceObserver.observe(document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: RESOURCE_ATTRS,
      })
    }
    startResourceObserver()
  } catch (err) {
    if (DEBUG) log('resource observer unavailable', err)
  }

  document.addEventListener('DOMContentLoaded', safe(function () {
    try {
      var list = document.querySelectorAll('[src],[href],[poster],[data-src]')
      for (var i = 0; i < list.length; i++) fixResourceNode(list[i])
    } catch (err) {
      if (DEBUG) log('initial sweep failed', err)
    }
    announceLocation()
    reportCapabilities()
  }, 'dom ready'))

  log('bridge ready')
})()
`
}
