/**
 * The dsh-overleaf bridge script. Served same-origin at
 * `/overleaf-workbench/bridge.js` and injected as an external classic script
 * right after `<head>` on every proxied HTML response (external same-origin
 * script survives strict `script-src 'self'` CSPs where inline handlers fail).
 *
 * Responsibilities:
 *  - Route every same-origin root-relative URL (fetch/XHR/EventSource/
 *    WebSocket/link/form/navigation) under the proxy prefix by combining a
 *    document-level `<base>` (written by the proxy rewrite) with defensive
 *    runtime wrappers installed here at document start.
 *  - Report text selections to the GUI shell (R5 quote pipeline source).
 *  - Insert generated text at the editor caret (R6) with a local snapshot +
 *    rollback buffer.
 *  - Scroll to & flash a quoted range when the composer chip asks (R5).
 */

/**
 * Raw browser-side script. Kept as one double-quoted-free normal TS string;
 * build copies it verbatim into the bundle.
 */
export const BRIDGE_SCRIPT_NAME = 'bridge.js'

export function renderBridgeScript(): string {
  return `/* dsh-overleaf bridge v1 (auto-generated by the plugin host; do not edit) */
;(function () {
  'use strict'
  var NS = 'dsh-overleaf'
  if (window.__DSH_OVERLEAF_BRIDGE__) return
  window.__DSH_OVERLEAF_BRIDGE__ = true
  var DEBUG = false
  function markDiagnostic(name, value) {
    try {
      if (document.documentElement) {
        document.documentElement.setAttribute('data-dsh-overleaf-' + name, String(value).slice(0, 300))
      }
    } catch (err) {}
  }
  markDiagnostic('bridge', 'ready')
  window.addEventListener('error', function (event) {
    markDiagnostic('last-error', event && event.message ? event.message : 'script-error')
  })
  window.addEventListener('unhandledrejection', function (event) {
    var reason = event && event.reason
    markDiagnostic('last-rejection', reason && reason.message ? reason.message : String(reason || 'unhandled-rejection'))
  })
  function log() {
    if (!DEBUG || !console || !console.debug) return
    Function.prototype.apply.call(console.debug, console, ['[dsh-overleaf]'].concat([].slice.call(arguments)))
  }
  function safe(fn, label) {
    return function () {
      try {
        return fn.apply(this, arguments)
      } catch (err) {
        if (DEBUG) log(label, err)
        return undefined
      }
    }
  }
  var PREFIX = '/overleaf-proxy'
  function sendToParent(message) {
    try {
      if (window.parent && window.parent !== window) {
        message.ns = NS
        window.parent.postMessage(message, '*')
      }
    } catch (err) {
      if (DEBUG) log('send failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Request routing helpers                                          */
  /* ---------------------------------------------------------------- */

  function isProxyUrl(value) {
    return typeof value === 'string' && (value.indexOf(PREFIX + '/') === 0)
  }

  /* User-content output-file origin (Overleaf serves PDFs/logs from a second
     host - compiles.overleafusercontent.com - announced in the shell meta tag
     ol-compilesUserContentDomain). The compile-result URL builder prepends
     that absolute host to output-file paths with window.origin semantics, so
     fetches escape the embedded origin and are CORS-blocked. Re-rooting them
     under the proxy lets the same-origin tunnel fetch the bytes (the locked
     main origin 404s on those paths). The meta may not be parsed yet while
     this script runs (it is injected right after <head>), so the lookup
     retries until it lands. */
  var contentOriginSeen = false
  var contentOriginValue = ''
  function readContentOrigin() {
    try {
      var metas = document.querySelectorAll('meta[name="ol-compilesUserContentDomain"], meta[name="ol-userContentDomain"]')
      for (var i = 0; i < metas.length; i++) {
        if (metas[i] && metas[i].content) return String(metas[i].content)
      }
    } catch (err) {}
    return undefined
  }
  function contentOrigin() {
    if (!contentOriginSeen) {
      var raw = readContentOrigin()
      if (raw !== undefined && raw !== '') {
        try {
          contentOriginValue = new URL(raw).origin
          markDiagnostic('content-origin', contentOriginValue)
        } catch (err) {
          contentOriginValue = ''
        }
        contentOriginSeen = true
      }
      /* else: meta not parsed yet - retry on the next request */
    }
    return contentOriginValue
  }

  function routeUrl(raw) {
    try {
      if (raw instanceof URL) raw = raw.toString()
      if (typeof raw !== 'string') return raw
      // Root-relative upstream URLs are re-rooted under the proxy.
      if (raw.charAt(0) === '/') {
        if (!isProxyUrl(raw)) return PREFIX + raw
        return raw
      }
      // Overleaf's compile result builder deliberately turns output-file paths
      // into absolute URLs with window.origin + file.url. Inside the embedded
      // page, window.origin is the DSH loopback shell, so those PDF/log fetches
      // bypass the proxy unless absolute same-origin URLs are re-rooted too.
      // Relative strings are left alone so the injected <base> keeps handling
      // their root semantics; external/CDN/blob/data origins remain untouched.
      var isAbsolute = raw.indexOf('//') === 0 || /^[a-z][a-z0-9+.-]*:/i.test(raw)
      if (isAbsolute) {
        var parsed = new URL(raw.indexOf('//') === 0 ? location.protocol + raw : raw)
        var isWorkbenchRoute = parsed.pathname.indexOf('/overleaf/workbench/') === 0
        var isAlreadyProxied = parsed.pathname === PREFIX || parsed.pathname.indexOf(PREFIX + '/') === 0
        if (parsed.origin === window.location.origin && !isWorkbenchRoute && !isAlreadyProxied) {
          return window.location.origin + PREFIX + parsed.pathname + parsed.search + parsed.hash
        }
        // Absolute URLs on the site's user-content output origin are re-rooted
        // under the proxy (keeps the path - the host proxy forwards zone paths
        // to that origin after learning it from the compile result).
        var contentDom = contentOrigin()
        if (contentDom !== '' && parsed.origin === contentDom && !isWorkbenchRoute && !isAlreadyProxied) {
          return PREFIX + parsed.pathname + parsed.search + parsed.hash
        }
      }
      return raw
    } catch (err) {
      return raw
    }
  }

  /* ---------------------------------------------------------------- */
  /* Compile-log capture (auto-fix source)                             */
  /*                                                                    */
  /* The panel's compile-fix tab needs the raw compiler output. Every    */
  /* compile POST and every output.pdf load passes the fetch/XHR        */
  /* wrappers below; when one is seen, the same build's output.log      */
  /* (and .blg) are fetched through the proxy and published to the      */
  /* shell. NOTE: this file is generated from a TS template literal -   */
  /* every regex backslash must be doubled, and no backtick or dollar-  */
  /* brace sequence may appear (even in comments).                      */
  /* ---------------------------------------------------------------- */
  var lastCompileStatus = undefined
  var lastCompileLogs = undefined
  var logFetchInFlight = false

  function pathnameOf(rawUrl) {
    try {
      if (rawUrl instanceof URL) rawUrl = rawUrl.toString()
      if (typeof rawUrl !== 'string' || rawUrl === '') return ''
      var absolute = rawUrl.indexOf('//') === 0
        ? location.protocol + rawUrl
        : (/^[a-z][a-z0-9+.-]*:/i.test(rawUrl) ? rawUrl : location.origin + (rawUrl.charAt(0) === '/' ? rawUrl : '/' + rawUrl))
      return new URL(absolute).pathname
    } catch (err) {
      return ''
    }
  }

  function isCompilePost(rawUrl) {
    return /^\\/project\\/[^/]+\\/compile\\/?$/.test(pathnameOf(rawUrl))
  }

  function isOutputPdf(rawUrl) {
    return /\\/output\\/output\\.pdf(?:[?#]|$)/.test(pathnameOf(rawUrl))
  }

  function truncateText(text, max) {
    if (typeof text !== 'string') return ''
    return text.length > max ? text.slice(0, max) + '\\n...[truncated]' : text
  }

  function fetchWithTimeout(url) {
    try {
      var controller = typeof AbortController === 'function' ? new AbortController() : undefined
      if (controller) setTimeout(function () { try { controller.abort() } catch (err) {} }, 30000)
      return window.fetch(url, {
        cache: 'no-store',
        signal: controller ? controller.signal : undefined,
      })
    } catch (err) {
      return Promise.reject(err)
    }
  }

  function publishCompileLog() {
    sendToParent({
      type: 'compile-log',
      status: lastCompileStatus || 'unknown',
      files: lastCompileLogs || [],
    })
  }

  function fetchAndPublishLog(fullUrl, pathName) {
    if (logFetchInFlight) return
    logFetchInFlight = true
    fetchWithTimeout(fullUrl)
      .then(function (response) {
        if (!response.ok) return { path: pathName, text: '', error: 'HTTP ' + response.status }
        return response.text().then(function (text) {
          return { path: pathName, text: truncateText(text, 262144) }
        })
      })
      .then(function (captured) {
        var previous = lastCompileLogs || []
        var rest = previous.filter(function (item) { return item && item.path !== pathName })
        lastCompileLogs = rest.concat([captured])
        publishCompileLog()
      })
      .catch(function (err) {
        if (DEBUG) log('compile log fetch failed', err)
      })
      .finally(function () { logFetchInFlight = false })
  }

  /* Observed on a compile POST response: read outputFiles, fetch every
     .log/.blg through the proxy with the same compileGroup/clsiServerId
     query the frontend uses. */
  function captureCompileResponse(json) {
    try {
      if (!json || !json.outputFiles || !Array.isArray(json.outputFiles)) return
      if (typeof json.status === 'string') lastCompileStatus = json.status
      var pdfDomain = typeof json.pdfDownloadDomain === 'string' ? json.pdfDownloadDomain : ''
      var params = new URLSearchParams()
      if (json.compileGroup) params.set('compileGroup', String(json.compileGroup))
      if (json.clsiServerId) params.set('clsiserverid', String(json.clsiServerId))
      params.set('enable_pdf_caching', 'true')
      var query = params.toString()
      var found = []
      for (var i = 0; i < json.outputFiles.length; i++) {
        var entry = json.outputFiles[i]
        var filePath = entry && typeof entry.path === 'string' ? entry.path : ''
        var relUrl = entry && typeof entry.url === 'string' ? entry.url : ''
        if (!/\\.(?:log|blg)$/i.test(filePath) || relUrl === '' || found.length >= 4) continue
        var target = pdfDomain !== '' && relUrl.charAt(0) === '/'
          ? pdfDomain + relUrl
          : relUrl
        found.push({ path: filePath, url: target + (query !== '' ? '?' + query : '') })
      }
      for (var j = 0; j < found.length; j++) {
        fetchAndPublishLog(found[j].url, found[j].path)
      }
    } catch (err) {
      if (DEBUG) log('compile capture failed', err)
    }
  }

  /* Fallback: an output.pdf load also reveals the build path - fetch the
     companion output.log with the SAME query the pdf request carried. */
  function captureLogFromOutputPdf(rawUrl) {
    try {
      var absolute = rawUrl.indexOf('//') === 0
        ? location.protocol + rawUrl
        : (/^[a-z][a-z0-9+.-]*:/i.test(rawUrl) ? rawUrl : location.origin + rawUrl)
      var parsed = new URL(absolute)
      if (!/\\.pdf$/i.test(parsed.pathname)) return
      parsed.pathname = parsed.pathname.replace(/\\.pdf$/i, '.log')
      fetchAndPublishLog(parsed.toString(), 'output.log')
    } catch (err) {
      if (DEBUG) log('pdf log fallback failed', err)
    }
  }

  function currentDocName() {
    try {
      var candidates = document.querySelectorAll('.document-title, [class*="document-title"], [class*="doc-title"], [class*="file-tree"] [class*="name"]')
      for (var i = 0; i < candidates.length; i++) {
        if (candidates[i] && candidates[i].textContent) {
          var text = String(candidates[i].textContent).trim()
          if (text !== '' && text.length < 120) return text
        }
      }
    } catch (err) {}
    return 'current-document'
  }

  /* Apply a validated edit list (each old must match once) to the live
     editor document, from the LAST edit backwards so ranges stay valid. */
  function applyFixEdits(edits) {
    try {
      if (!Array.isArray(edits) || edits.length === 0) {
        sendToParent({ type: 'fix-applied', ok: false, error: 'no-edits' })
        return
      }
      var cm5 = findCm5()
      if (cm5) {
        var doc5 = String(cm5.getValue())
        var steps5 = buildFixSteps(edits, doc5)
        if (!steps5.ok) { sendToParent({ type: 'fix-applied', ok: false, error: steps5.error, detail: steps5.detail }); return }
        rememberSnapshot(doc5)
        var sorted5 = steps5.steps.slice().sort(function (a, b) { return b.from - a.from })
        for (var s5 = 0; s5 < sorted5.length; s5++) {
          cm5.replaceRange(sorted5[s5].replacement, cm5.posFromIndex(sorted5[s5].from), cm5.posFromIndex(sorted5[s5].to))
        }
        cm5.focus()
        sendToParent({ type: 'fix-applied', ok: true, applied: sorted5.length })
        return
      }
      var cm6 = findCm6()
      if (cm6) {
        var doc6 = cm6.state.doc.toString()
        var steps6 = buildFixSteps(edits, doc6)
        if (!steps6.ok) { sendToParent({ type: 'fix-applied', ok: false, error: steps6.error, detail: steps6.detail }); return }
        rememberSnapshot(doc6)
        var sorted6 = steps6.steps.slice().sort(function (a, b) { return b.from - a.from })
        cm6.dispatch({
          changes: sorted6.map(function (step) { return { from: step.from, to: step.to, insert: step.replacement } }),
        })
        cm6.focus()
        sendToParent({ type: 'fix-applied', ok: true, applied: sorted6.length })
        return
      }
      sendToParent({ type: 'fix-applied', ok: false, error: 'no-editor' })
    } catch (err) {
      sendToParent({ type: 'fix-applied', ok: false, error: err && err.message ? err.message : String(err) })
    }
  }

  function buildFixSteps(edits, doc) {
    var steps = []
    for (var i = 0; i < edits.length; i++) {
      var edit = edits[i]
      var oldText = edit && typeof edit.old === 'string' ? edit.old : ''
      var newText = edit && typeof edit.new === 'string' ? edit.new : ''
      if (oldText === '') return { ok: false, error: 'empty-old' }
      if (oldText.length > doc.length) return { ok: false, error: 'not-found', detail: oldText.slice(0, 80) }
      var first = doc.indexOf(oldText)
      if (first < 0) return { ok: false, error: 'not-found', detail: oldText.slice(0, 80) }
      if (doc.indexOf(oldText, first + 1) >= 0) return { ok: false, error: 'not-unique', detail: oldText.slice(0, 80) }
      steps.push({ from: first, to: first + oldText.length, replacement: newText })
    }
    return { ok: true, steps: steps }
  }

  function clickRecompile() {
    try {
      var candidates = document.querySelectorAll('button, [role="button"], [aria-label]')
      for (var i = 0; i < candidates.length; i++) {
        var el = candidates[i]
        var aria = String(el.getAttribute && el.getAttribute('aria-label') || '')
        var title = String(el.getAttribute && el.getAttribute('title') || '')
        var label = String(el.textContent || '').trim()
        if (/^(recompile|compile|重新编译|编译)$/i.test(label) || /^recompile$/i.test(aria) || /^recompile$/i.test(title)) {
          (function (target) {
            setTimeout(function () { try { target.click() } catch (err) {} }, 0)
          })(el)
          sendToParent({ type: 'recompile-clicked', ok: true })
          return
        }
      }
      sendToParent({ type: 'recompile-clicked', ok: false })
    } catch (err) {
      sendToParent({ type: 'recompile-clicked', ok: false })
    }
  }

  /* fetch wrapper */
  var originalFetch = null
  if (typeof window.fetch === 'function') {
    originalFetch = window.fetch
    window.fetch = safe(function (input, init) {
      var rawUrl = typeof input === 'string' ? input : (typeof Request === 'function' && input instanceof Request ? input.url : '')
      if (typeof input === 'string' || input instanceof URL) {
        arguments[0] = routeUrl(input)
      } else if (typeof Request === 'function' && input instanceof Request) {
        // Some PDF loaders pre-build a Request from the absolute output URL.
        // Clone it with the routed URL so method, headers, body and signal are
        // retained while the destination moves under /overleaf-proxy.
        try {
          var routedRequestUrl = routeUrl(input.url)
          if (routedRequestUrl !== input.url) arguments[0] = new Request(routedRequestUrl, input)
        } catch (requestError) {
          if (DEBUG) log('request url fix failed', requestError)
        }
      }
      var routedResult = originalFetch.apply(window, arguments)
      // Compile-fix source: compile POST responses reveal output.log/.blg URLs;
      // an output.pdf load reveals the build path as a fallback.
      if (rawUrl !== '' && isCompilePost(rawUrl)) {
        var fetchMethod = String((init && init.method) || (typeof Request === 'function' && input instanceof Request ? input.method : 'GET')).toUpperCase()
        if (fetchMethod === 'POST') {
          routedResult
            .then(function (response) {
              try {
                response.clone().json()
                  .then(function (json) { captureCompileResponse(json) })
                  .catch(function () {})
              } catch (err) {
                if (DEBUG) log('compile clone failed', err)
              }
            })
            .catch(function () {})
        }
      } else if (rawUrl !== '' && isOutputPdf(rawUrl)) {
        setTimeout(function () { captureLogFromOutputPdf(rawUrl) }, 0)
      }
      return routedResult
    }, 'fetch wrap')
  }

  /* XMLHttpRequest.open wrapper */
  try {
    var proto = window.XMLHttpRequest && window.XMLHttpRequest.prototype
    if (proto && typeof proto.open === 'function') {
      var originalOpen = proto.open
      proto.open = safe(function (method, url) {
        var rawUrl = typeof url === 'string' ? url : ''
        if (typeof url === 'string') {
          arguments[1] = routeUrl(url)
        }
        // XHR backup for the compile-log source (some deployments/issues use
        // XHR for the compile POST - the fetch wrapper alone would miss them).
        if (rawUrl !== '' && typeof this.addEventListener === 'function') {
          try {
            var xhr = this
            xhr.addEventListener('readystatechange', function () {
              if (xhr.readyState !== 4) return
              try {
                if (isCompilePost(rawUrl) && xhr.status === 200 && typeof xhr.responseText === 'string' && xhr.responseText !== '') {
                  var parsedPayload = JSON.parse(xhr.responseText)
                  if (parsedPayload) captureCompileResponse(parsedPayload)
                } else if (isOutputPdf(rawUrl)) {
                  captureLogFromOutputPdf(rawUrl)
                }
              } catch (err) {
                if (DEBUG) log('xhr compile capture failed', err)
              }
            })
          } catch (err) {
            if (DEBUG) log('xhr hook failed', err)
          }
        }
        return originalOpen.apply(this, arguments)
      }, 'xhr wrap')
    }
  } catch (err) {
    if (DEBUG) log('xhr patch skipped', err)
  }

  /* EventSource wrapper.

     MUST use class extends: EventSource is a real DOM constructor and cannot
     be invoked via .call() — the previous prototype-shuffle wrapper made
     EVERY new EventSource(...) on the page throw
     "Failed to construct 'EventSource'" and broke all SSE consumers. */
  try {
    if (typeof window.EventSource === 'function') {
      var OriginalEventSource = window.EventSource
      class PatchedEventSource extends OriginalEventSource {
        constructor(url, config) {
          if (typeof url === 'string') url = routeUrl(url)
          super(url, config)
        }
      }
      Object.defineProperty(PatchedEventSource, 'name', { value: 'EventSource' })
      window.EventSource = PatchedEventSource
    }
  } catch (err) {
    if (DEBUG) log('eventsource patch skipped', err)
  }

  /* WebSocket transport (socket.io websocket upgrade path).

     The webserver's upgrade registry is exact-path only and cannot host
     socket.io's dynamic upgrade URLs, so the plugin runs a companion tunnel
     on its own loopback port (injected as __DSH_OVERLEAF_WS_PORT__). When
     that port is known, same-origin WebSocket targets are redirected there;
     the tunnel forwards the request verbatim to the upstream origin. */
  try {
    var OriginalWebSocket = window.WebSocket
    if (typeof OriginalWebSocket === 'function') {
      var WS_PORT = parseInt(window.__DSH_OVERLEAF_WS_PORT__, 10) || 0
      markDiagnostic('ws-port', WS_PORT)
      function PatchedWebSocket(url, protocols) {
        try {
          if (typeof url === 'string' && url.indexOf('//') === 0) {
            url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + url
          }
          if (typeof url === 'string' && url.charAt(0) === '/') {
            if (WS_PORT > 0) {
              url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + '127.0.0.1:' + WS_PORT + url
            } else {
              url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + window.location.host + PREFIX + url
            }
          } else if (typeof url === 'string' && url.indexOf(window.location.host) !== -1 && !isProxyUrl(url)) {
            if (WS_PORT > 0) {
              var parts = url.split(window.location.host)
              url = parts[0] + '127.0.0.1:' + WS_PORT + parts.slice(1).join(window.location.host)
            } else {
              url = url.replace(location.protocol + '//' + window.location.host,
                location.protocol + '//' + window.location.host + PREFIX)
            }
          }
        } catch (err) {
          if (DEBUG) log('ws url fix failed', err)
        }
        var socketUrl = String(url)
        try {
          var parsedSocketUrl = new URL(socketUrl)
          markDiagnostic('ws-target', parsedSocketUrl.host)
        } catch (err) {
          markDiagnostic('ws-target', 'invalid-url')
        }
        markDiagnostic('ws-state', 'connecting')
        var socket = new OriginalWebSocket(url, protocols)
        socket.addEventListener('open', function () { markDiagnostic('ws-state', 'open') })
        socket.addEventListener('error', function () { markDiagnostic('ws-state', 'error') })
        socket.addEventListener('close', function (event) {
          markDiagnostic('ws-state', 'closed:' + String(event && event.code || 0))
        })
        return socket
      }
      Object.defineProperty(PatchedWebSocket, 'name', { value: 'WebSocket' })
      // Preserve the native constructor contract. Overleaf compares its
      // connection state against WebSocket.OPEN/CLOSED before it ever creates
      // a socket; dropping those static constants makes both sides undefined
      // and canReconnect() stays false forever. Sharing the native prototype
      // also keeps event.target instanceof WebSocket true after wrapping.
      Object.setPrototypeOf(PatchedWebSocket, OriginalWebSocket)
      PatchedWebSocket.prototype = OriginalWebSocket.prototype
      window.WebSocket = PatchedWebSocket
    }
  } catch (err) {
    if (DEBUG) log('websocket patch skipped', err)
  }

  /* navigator.sendBeacon wrapper (analytics endpoints like /event/* are
     POSTed through it and would otherwise bypass the proxy). */
  try {
    if (navigator.sendBeacon && !navigator.sendBeacon.__dshOverleafWrapped) {
      var originalSendBeacon = navigator.sendBeacon.bind(navigator)
      var wrappedSendBeacon = function (url, data) {
        try {
          if (typeof url === 'string') url = routeUrl(url)
        } catch (err) {
          if (DEBUG) log('beacon url fix failed', err)
        }
        return originalSendBeacon(url, data)
      }
      wrappedSendBeacon.__dshOverleafWrapped = true
      Object.defineProperty(navigator, 'sendBeacon', { value: wrappedSendBeacon, configurable: true })
    }
  } catch (err) {
    if (DEBUG) log('sendBeacon patch skipped', err)
  }

  /* Resource-load failure fallback (capture phase - resource errors do not
     bubble). If an IMG/SCRIPT/LINK failed on an un-prefixed root-relative
     URL that slipped past every other rewriter, rebase it in place once and
     let the browser retry. */
  try {
    document.addEventListener('error', safe(function (event) {
      try {
        var el = event.target
        if (!el || el.nodeType !== 1 || !el.getAttribute) return
        var tag = el.tagName
        var attr = tag === 'IMG' ? 'src' : tag === 'SCRIPT' ? 'src' : tag === 'LINK' ? 'href' : null
        if (attr === null) return
        var value = el.getAttribute(attr)
        if (typeof value !== 'string' || value.charAt(0) !== '/' || value.indexOf(PREFIX) === 0
          || value.indexOf('/overleaf/workbench/') === 0) return
        if (el.getAttribute('data-dsh-retried')) return
        el.setAttribute('data-dsh-retried', '1')
        el.setAttribute(attr, PREFIX + value)
      } catch (err) {}
    }, 'resource error fallback'), true)
  } catch (err) {
    if (DEBUG) log('resource fallback skipped', err)
  }

  /* ---------------------------------------------------------------- */
  /* CodeMirror / editor probes                                       */
  /* ---------------------------------------------------------------- */

  function findCm5() {
    try {
      var holders = Array.prototype.slice.call(document.querySelectorAll('.CodeMirror'))
      var instances = []
      for (var i = 0; i < holders.length; i++) {
        var inst = holders[i].CodeMirror
        if (inst) instances.push(inst)
      }
      if (instances.length === 0) return undefined
      var focused = instances.filter(function (cm) { return cm.hasFocus && cm.hasFocus() })
      if (focused.length > 0) return focused[0]
      return instances[0]
    } catch (err) {
      return undefined
    }
  }

  /* Locate the live CodeMirror 6 EditorView. @codemirror/view stores the
     view on the .cm-editor DOM node under the key "cmView", but that field
     is a ContentView wrapper - the EditorView itself sits on its "view"
     property (and may be nested one level deeper), so unwrap before
     validating. NOTE: no backticks or dollar-brace sequences are allowed
     inside this template literal (see v0.1.10 lesson). */
  function asEditorView(candidate) {
    var hop = candidate
    for (var depth = 0; hop && depth < 4; depth++) {
      try {
        if (hop.state && hop.state.doc && typeof hop.dispatch === 'function') return hop
      } catch (err) {}
      hop = hop.view
    }
    return undefined
  }

  function findCm6() {
    try {
      var roots = document.querySelectorAll('.cm-editor')
      for (var i = 0; i < roots.length; i++) {
        var holder = roots[i]
        var direct = asEditorView(holder.cmView)
          || asEditorView(holder.editor)
          || asEditorView(holder.parentNode && holder.parentNode.__codemirrorView)
        if (direct) return direct
        var inner = holder.querySelector && holder.querySelector('.cm-scroller')
        if (inner) {
          var viaInner = asEditorView(inner.cmView)
          if (viaInner) return viaInner
        }
      }
      /* Last resort: scan own properties of editor DOM nodes for an object
         shaped like an EditorView (state.doc + dispatch). */
      var nodes = document.querySelectorAll('.cm-editor, .cm-content, .cm-scroller')
      for (var n = 0; n < nodes.length; n++) {
        var keys = Object.keys(nodes[n] || {})
        for (var k = 0; k < keys.length; k++) {
          var value = null
          try { value = nodes[n][keys[k]] } catch (err) { continue }
          var found = asEditorView(value)
          if (found) return found
        }
      }
      return undefined
    } catch (err) {
      return undefined
    }
  }

  function editorKind(cm) {
    if (!cm) return 'none'
    if (typeof cm.replaceSelection === 'function') return 'cm5'
    if (cm.state && typeof cm.dispatch === 'function') return 'cm6'
    return 'unknown'
  }

  var savedSelection = undefined
  var selectionSequence = 0

  /* Capture editor-native offsets, not just DOM selection text. The stable
     token lets the shell request a delayed replacement after an agent run. */
  function captureEditorSelection() {
    try {
      var cm5 = findCm5()
      if (cm5 && typeof cm5.getCursor === 'function' && typeof cm5.indexFromPos === 'function') {
        var doc5 = String(cm5.getValue())
        var anchor5 = cm5.indexFromPos(cm5.getCursor('anchor'))
        var head5 = cm5.indexFromPos(cm5.getCursor('head'))
        var from5 = Math.min(anchor5, head5)
        var to5 = Math.max(anchor5, head5)
        if (from5 !== to5) return rememberEditorSelection('cm5', cm5, from5, to5, doc5)
      }
      var cm6 = findCm6()
      if (cm6 && cm6.state && cm6.state.selection) {
        var main6 = cm6.state.selection.main
        var from6 = Math.min(main6.from, main6.to)
        var to6 = Math.max(main6.from, main6.to)
        if (from6 !== to6) return rememberEditorSelection('cm6', cm6, from6, to6, cm6.state.doc.toString())
      }
    } catch (err) {
      if (DEBUG) log('editor selection capture failed', err)
    }
    return undefined
  }

  function rememberEditorSelection(engine, editor, from, to, doc) {
    var text = doc.slice(from, to)
    if (!text.trim()) return undefined
    if (savedSelection && savedSelection.engine === engine && savedSelection.editor === editor && savedSelection.from === from
      && savedSelection.to === to && savedSelection.text === text) return savedSelection
    selectionSequence += 1
    savedSelection = {
      id: 'selection-' + Date.now() + '-' + selectionSequence,
      engine: engine,
      editor: editor,
      from: from,
      to: to,
      text: text,
      before: doc.slice(Math.max(0, from - 48), from),
      after: doc.slice(to, Math.min(doc.length, to + 48)),
    }
    return savedSelection
  }

  function replacementTargetStillMatches(target, doc) {
    if (doc.slice(target.from, target.to) !== target.text) return false
    var beforeStart = Math.max(0, target.from - target.before.length)
    if (doc.slice(beforeStart, target.from) !== target.before) return false
    return doc.slice(target.to, target.to + target.after.length) === target.after
  }

  function selectionEditorIsAttached(target) {
    try {
      var node = target.engine === 'cm5' && target.editor && typeof target.editor.getWrapperElement === 'function'
        ? target.editor.getWrapperElement()
        : target.editor && (target.editor.dom || target.editor.scrollDOM)
      return !!node && document.documentElement.contains(node)
    } catch (err) {
      return false
    }
  }

  function replaceSavedEditorSelection(id, replacement) {
    if (!savedSelection || savedSelection.id !== id) {
      sendToParent({ type: 'selection-replace-done', ok: false, error: 'selection-expired' })
      return
    }
    var target = savedSelection
    try {
      if (target.engine === 'cm5') {
        var cm5 = target.editor
        var doc5 = cm5 && String(cm5.getValue())
        if (!cm5 || !selectionEditorIsAttached(target) || !replacementTargetStillMatches(target, doc5)) throw new Error('selection-stale')
        rememberSnapshot(doc5)
        cm5.replaceRange(replacement, cm5.posFromIndex(target.from), cm5.posFromIndex(target.to))
        cm5.setCursor(cm5.posFromIndex(target.from + replacement.length))
        cm5.focus()
      } else if (target.engine === 'cm6') {
        var cm6 = target.editor
        var doc6 = cm6 && cm6.state.doc.toString()
        if (!cm6 || !selectionEditorIsAttached(target) || !replacementTargetStillMatches(target, doc6)) throw new Error('selection-stale')
        rememberSnapshot(doc6)
        cm6.dispatch({
          changes: { from: target.from, to: target.to, insert: replacement },
          selection: { anchor: target.from + replacement.length },
        })
        cm6.focus()
      } else {
        throw new Error('selection-engine-unavailable')
      }
      savedSelection = undefined
      sendToParent({ type: 'selection-replace-done', ok: true, engine: target.engine })
    } catch (err) {
      sendToParent({ type: 'selection-replace-done', ok: false, error: err && err.message })
    }
  }

  function insertViaCm5(cm, text) {
    var snapshot = String(cm.getValue())
    rememberSnapshot(snapshot)
    cm.replaceSelection(text)
    cm.focus()
    return true
  }

  function insertViaCm6(view, text) {
    var state = view.state
    var snapshot = state.doc.toString()
    rememberSnapshot(snapshot)
    var from = state.selection.main.from
    var to = state.selection.main.to
    view.dispatch({ changes: { from: from, to: to, insert: text }, selection: { anchor: from + text.length } })
    view.focus()
    return true
  }

  function insertFallback(text) {
    var active = document.activeElement
    var editable = active && (active.tagName === 'TEXTAREA' || active.isContentEditable)
    if (editable && document.execCommand) {
      document.execCommand('insertText', false, text)
      return true
    }
    var holder = document.querySelector('.ace_text-input')
    if (holder) {
      holder.focus()
      if (document.execCommand) {
        document.execCommand('insertText', false, text)
        return true
      }
    }
    return false
  }

  /* ---------------------------------------------------------------- */
  /* Snapshot buffer (rollback)                                       */
  /* ---------------------------------------------------------------- */

  var SNAPSHOT_KEY = 'dsh-overleaf:snapshot'
  function readDocValue() {
    try {
      var cm5 = findCm5()
      if (cm5) return String(cm5.getValue())
      var cm6 = findCm6()
      if (cm6) return cm6.state.doc.toString()
      return undefined
    } catch (err) {
      return undefined
    }
  }

  /* Cursor context for AI prompts: the text around the caret plus the caret
     offset, so the agent can ground its edit in the real document. */
  function readCursorContext(radius) {
    try {
      var docValue = readDocValue()
      if (docValue === undefined) return undefined
      var text = String(docValue)
      var cursor = -1
      var cm5 = findCm5()
      if (cm5) {
        try { cursor = cm5.indexFromPos(cm5.getCursor()) } catch (err) { cursor = -1 }
      } else {
        var cm6 = findCm6()
        if (cm6) {
          try { cursor = cm6.state.selection.main.head } catch (err2) { cursor = -1 }
        }
      }
      if (cursor < 0) cursor = 0
      var r = Number(radius) || 1200
      var from = Math.max(0, cursor - r)
      var to = Math.min(text.length, cursor + r)
      return {
        cursor: cursor,
        docLength: text.length,
        before: text.slice(from, cursor),
        after: text.slice(cursor, to),
      }
    } catch (err) {
      return undefined
    }
  }
  function rememberSnapshot(docValue) {
    try {
      if (docValue === undefined || docValue === null) return
      window.localStorage.setItem(SNAPSHOT_KEY, JSON.stringify({
        time: Date.now(),
        doc: docValue,
      }))
      sendToParent({ type: 'snapshot-saved' })
    } catch (err) {
      if (DEBUG) log('snapshot failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Parent command handling                                          */
  /* ---------------------------------------------------------------- */

  window.addEventListener('message', safe(function (event) {
    if (event.source !== window.parent) return
    var data = event.data
    if (!data || data.ns !== NS) return
    if (data.type === 'insert') {
      try {
        var cm5 = findCm5()
        if (cm5) {
          insertViaCm5(cm5, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm5' })
          return
        }
        var cm6 = findCm6()
        if (cm6) {
          insertViaCm6(cm6, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm6' })
          return
        }
        var fellBack = insertFallback(String(data.text || ''))
        sendToParent({ type: 'insert-done', ok: !!fellBack, engine: fellBack ? 'fallback' : 'none',
          error: fellBack ? undefined : 'editor API not detected; paste manually from the reply' })
      } catch (err) {
        sendToParent({ type: 'insert-done', ok: false, error: err && err.message })
      }
      return
    }
    if (data.type === 'snapshot') {
      rememberSnapshot(readDocValue())
      return
    }
    if (data.type === 'selection-request') {
      emitSelection(true)
      return
    }
    if (data.type === 'replace-selection') {
      replaceSavedEditorSelection(String(data.selectionId || ''), String(data.text || ''))
      return
    }
    if (data.type === 'compile-log-request') {
      publishCompileLog()
      return
    }
    if (data.type === 'document-request') {
      try {
        var docText = readDocValue()
        if (docText === undefined) {
          sendToParent({ type: 'document', name: 'current-document', text: '', error: 'no-editor' })
          return
        }
        var fullDoc = String(docText)
        var cappedDoc = truncateText(fullDoc, 200000)
        sendToParent({
          type: 'document',
          name: currentDocName(),
          text: cappedDoc,
          truncated: cappedDoc.length < fullDoc.length,
        })
      } catch (err) {
        sendToParent({ type: 'document', name: 'current-document', text: '', error: err && err.message })
      }
      return
    }
    if (data.type === 'apply-fix-edits') {
      applyFixEdits(data.edits)
      return
    }
    if (data.type === 'recompile-click') {
      clickRecompile()
      return
    }
    if (data.type === 'reveal') {
      revealText(String(data.query || ''))
      return
    }
    if (data.type === 'outline-request') {
      sendOutline()
      return
    }
    if (data.type === 'cursor-context-request') {
      try {
        var cc = readCursorContext(data.radius)
        if (cc === undefined) {
          sendToParent({ type: 'cursor-context', error: 'no-editor' })
        } else {
          sendToParent({ type: 'cursor-context', cursor: cc.cursor, docLength: cc.docLength, before: cc.before, after: cc.after })
        }
      } catch (err) {
        sendToParent({ type: 'cursor-context', error: err && err.message })
      }
      return
    }
    if (data.type === 'debug') {
      DEBUG = true
      return
    }
  }, 'message handler'), false)

  /* Extract a LaTeX section/subsection outline from the live editor document. */
  function sendOutline() {
    try {
      var docValue = readDocValue()
      var cm5 = findCm5()
      var cm6 = cm5 ? undefined : findCm6()
      var engine = cm5 ? 'cm5' : (cm6 ? 'cm6' : 'none')
      var debug = { engine: engine, url: location.href }
      if (docValue === undefined) {
        sendToParent({ type: 'outline', items: [], error: 'no-editor', debug: debug })
        return
      }
      /* NOTE: inside this TS template literal every backslash that must
         survive into the generated JS is doubled (\\n, \\s, \\{). A single
         \n here becomes a REAL newline in the served script and breaks it. */
      var lines = String(docValue).split('\\n')
      var items = []
      /* Starred (unnumbered) sections are outline entries too. */
      var pattern = /^(part|chapter|section|subsection|subsubsection)\\*?\\s*\\{([^}]*)\\}/
      for (var i = 0; i < lines.length; i++) {
        var match = pattern.exec(lines[i])
        if (!match) continue
        items.push({
          level: match[1],
          title: match[2].trim(),
          line: i,
          text: lines[i],
        })
        if (items.length >= 300) break
      }
      debug.chars = String(docValue).length
      debug.hits = items.length
      sendToParent({ type: 'outline', items: items, debug: debug })
    } catch (err) {
      sendToParent({ type: 'outline', items: [], error: err && err.message })
    }
  }

  /* Report whether the caret insertion works right now (toolbar health). */
  function reportCapabilities() {
    var kind = 'none'
    if (findCm5()) kind = 'cm5'
    else if (findCm6()) kind = 'cm6'
    sendToParent({ type: 'capabilities', editor: kind })
  }
  setTimeout(safe(reportCapabilities, 'cap probe'), 1200)

  /* ---------------------------------------------------------------- */
  /* Selection reporting (R5 source side)                             */
  /* ---------------------------------------------------------------- */

  var lastSelectionSentAt = 0
  function emitSelection(force) {
    try {
      var editorSelection = captureEditorSelection()
      if (editorSelection) {
        var editorNow = Date.now()
        if (!force && editorNow - lastSelectionSentAt < 80) return
        lastSelectionSentAt = editorNow
        sendToParent({
          type: 'selection',
          text: editorSelection.text,
          selectionId: editorSelection.id,
          engine: editorSelection.engine,
          rect: { left: 0, top: 0, right: 0, bottom: 0 },
        })
        return
      }
      var sel = window.getSelection()
      if (!sel || sel.rangeCount === 0 || sel.isCollapsed) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var text = sel.toString()
      if (!text.trim()) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var now = Date.now()
      if (!force && now - lastSelectionSentAt < 80) return
      lastSelectionSentAt = now
      var range = sel.getRangeAt(0)
      var rect = { left: 0, top: 0, right: 0, bottom: 0 }
      try {
        var box = range.getBoundingClientRect()
        rect = { left: box.left, top: box.top, right: box.right, bottom: box.bottom }
      } catch (ignoredRectError) {}
      sendToParent({ type: 'selection', text: text, engine: 'dom', rect: rect })
    } catch (err) {
      if (DEBUG) log('selection emit failed', err)
    }
  }
  document.addEventListener('selectionchange', safe(function () { emitSelection(false) }, 'selectionchange'), true)
  document.addEventListener('keyup', safe(function () { emitSelection(false) }, 'keyup-selection'), true)

  /* ---------------------------------------------------------------- */
  /* Reveal + flash (chip jump-back target)                           */
  /* ---------------------------------------------------------------- */

  function revealText(query) {
    try {
      if (!query) return
      var needle = query.replace(/^\\n+|\\n+$/g, '').slice(0, 200)
      if (!needle) return
      var cm5 = findCm5()
      if (cm5) {
        var doc = String(cm5.getValue())
        var index = doc.indexOf(needle)
        if (index >= 0) {
          var from = cm5.posFromIndex(index)
          var to = cm5.posFromIndex(index + Math.min(needle.length, 400))
          cm5.setSelection(from, to)
          cm5.scrollIntoView({ from: from, to: to }, 160)
          cm5.focus()
          return
        }
      }
      /* DOM-wide soft match otherwise */
      var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false)
      while (walker.nextNode()) {
        var node = walker.currentNode
        if (node.nodeValue && node.nodeValue.indexOf(needle.slice(0, 60)) !== -1) {
          var parentEl = node.parentElement
          if (parentEl) {
            parentEl.scrollIntoView({ block: 'center', behavior: 'smooth' })
            var previousShadow = parentEl.style.boxShadow
            parentEl.style.boxShadow = '0 0 0 3px rgba(64,156,255,0.65)'
            setTimeout(function () { parentEl.style.boxShadow = previousShadow }, 1600)
            return
          }
        }
      }
    } catch (err) {
      if (DEBUG) log('reveal failed', err)
    }
  }

  /* Notify the shell whenever the embedded URL changes (toolbar breadcrumb). */
  function announceLocation() {
    sendToParent({ type: 'url-change', href: window.location.href })
  }
  announceLocation()
  window.addEventListener('popstate', safe(announceLocation, 'popstate'))

  /* ---------------------------------------------------------------- */
  /* Dynamic resource routing                                         */
  /*                                                                  */
  /* The proxy rewrites the INITIAL HTML server-side, but SPAs (TeXPage */
  /* dashboards, Overleaf loaders) insert scripts/styles/images at     */
  /* runtime with root-relative URLs; those would fall out of the      */
  /* proxy and hit the GUI shell's own fallback routes. Sweep existing */
  /* nodes once the DOM is ready, then watch every insertion/attribute */
  /* change and rebase matching URLs in place.                         */
  /* ---------------------------------------------------------------- */

  var RESOURCE_ATTRS = ['src', 'href', 'poster', 'data-src']
  function fixResourceNode(el) {
    try {
      if (!el || el.nodeType !== 1 || !el.hasAttribute) return
      for (var i = 0; i < RESOURCE_ATTRS.length; i++) {
        var attr = RESOURCE_ATTRS[i]
        if (!el.hasAttribute(attr)) continue
        var value = el.getAttribute(attr)
        if (typeof value !== 'string') continue
        if (value.indexOf('/overleaf/workbench/') === 0) continue
        var routed = routeUrl(value)
        if (routed !== value) el.setAttribute(attr, routed)
      }
    } catch (err) {
      if (DEBUG) log('fixResourceNode failed', err)
    }
  }
  try {
    var resourceObserver = new MutationObserver(function (mutations) {
      for (var i = 0; i < mutations.length; i++) {
        var mutation = mutations[i]
        if (mutation.type === 'attributes') {
          fixResourceNode(mutation.target)
          continue
        }
        for (var j = 0; j < mutation.addedNodes.length; j++) {
          var added = mutation.addedNodes[j]
          fixResourceNode(added)
          if (added && added.querySelectorAll) {
            var list = added.querySelectorAll('[src],[href],[poster],[data-src]')
            for (var k = 0; k < list.length; k++) fixResourceNode(list[k])
          }
        }
      }
    })
    function startResourceObserver() {
      if (!document.documentElement) {
        setTimeout(startResourceObserver, 50)
        return
      }
      resourceObserver.observe(document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: RESOURCE_ATTRS,
      })
    }
    startResourceObserver()
  } catch (err) {
    if (DEBUG) log('resource observer unavailable', err)
  }

  document.addEventListener('DOMContentLoaded', safe(function () {
    try {
      var list = document.querySelectorAll('[src],[href],[poster],[data-src]')
      for (var i = 0; i < list.length; i++) fixResourceNode(list[i])
    } catch (err) {
      if (DEBUG) log('initial sweep failed', err)
    }
    announceLocation()
    reportCapabilities()
  }, 'dom ready'))

  log('bridge ready')
})()
`
}
