/**
 * The dsh-overleaf bridge script. Served same-origin at
 * `/overleaf-workbench/bridge.js` and injected as an external classic script
 * right after `<head>` on every proxied HTML response (external same-origin
 * script survives strict `script-src 'self'` CSPs where inline handlers fail).
 *
 * Responsibilities:
 *  - Route every same-origin root-relative URL (fetch/XHR/EventSource/
 *    WebSocket/link/form/navigation) under the proxy prefix by combining a
 *    document-level `<base>` (written by the proxy rewrite) with defensive
 *    runtime wrappers installed here at document start.
 *  - Report text selections to the GUI shell (R5 quote pipeline source).
 *  - Insert generated text at the editor caret (R6) with a local snapshot +
 *    rollback buffer.
 *  - Scroll to & flash a quoted range when the composer chip asks (R5).
 */

/**
 * Raw browser-side script. Kept as one double-quoted-free normal TS string;
 * build copies it verbatim into the bundle.
 */
export const BRIDGE_SCRIPT_NAME = 'bridge.js'

export function renderBridgeScript(): string {
  return `/* dsh-overleaf bridge v1 (auto-generated by the plugin host; do not edit) */
;(function () {
  'use strict'
  var NS = 'dsh-overleaf'
  if (window.__DSH_OVERLEAF_BRIDGE__) return
  window.__DSH_OVERLEAF_BRIDGE__ = true
  var DEBUG = false
  function markDiagnostic(name, value) {
    try {
      if (document.documentElement) {
        document.documentElement.setAttribute('data-dsh-overleaf-' + name, String(value).slice(0, 300))
      }
    } catch (err) {}
  }
  markDiagnostic('bridge', 'ready')
  window.addEventListener('error', function (event) {
    markDiagnostic('last-error', event && event.message ? event.message : 'script-error')
  })
  window.addEventListener('unhandledrejection', function (event) {
    var reason = event && event.reason
    markDiagnostic('last-rejection', reason && reason.message ? reason.message : String(reason || 'unhandled-rejection'))
  })
  function log() {
    if (!DEBUG || !console || !console.debug) return
    Function.prototype.apply.call(console.debug, console, ['[dsh-overleaf]'].concat([].slice.call(arguments)))
  }
  function safe(fn, label) {
    return function () {
      try {
        return fn.apply(this, arguments)
      } catch (err) {
        if (DEBUG) log(label, err)
        return undefined
      }
    }
  }
  var PREFIX = '/overleaf-proxy'
  function sendToParent(message) {
    try {
      if (window.parent && window.parent !== window) {
        message.ns = NS
        window.parent.postMessage(message, '*')
      }
    } catch (err) {
      if (DEBUG) log('send failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Request routing helpers                                          */
  /* ---------------------------------------------------------------- */

  function isProxyUrl(value) {
    return typeof value === 'string' && (value.indexOf(PREFIX + '/') === 0)
  }
  function routeUrl(raw) {
    try {
      if (raw instanceof URL) raw = raw.toString()
      if (typeof raw !== 'string') return raw
      // Absolute URLs pointing at THIS loopback shell outside the proxy are
      // re-rooted under the proxy; other hosts stay untouched.
      if (raw.charAt(0) === '/') {
        if (!isProxyUrl(raw)) return PREFIX + raw
        return raw
      }
      // Protocol-relative or absolute same-host URLs keep their scheme choice;
      // proxy-resolved already; leave everything else alone.
      return raw
    } catch (err) {
      return raw
    }
  }

  /* fetch wrapper */
  var originalFetch = null
  if (typeof window.fetch === 'function') {
    originalFetch = window.fetch
    window.fetch = safe(function (input, init) {
      if (typeof input === 'string' || input instanceof URL) {
        arguments[0] = routeUrl(input)
      }
      return originalFetch.apply(window, arguments)
    }, 'fetch wrap')
  }

  /* XMLHttpRequest.open wrapper */
  try {
    var proto = window.XMLHttpRequest && window.XMLHttpRequest.prototype
    if (proto && typeof proto.open === 'function') {
      var originalOpen = proto.open
      proto.open = safe(function (method, url) {
        if (typeof url === 'string') {
          arguments[1] = routeUrl(url)
        }
        return originalOpen.apply(this, arguments)
      }, 'xhr wrap')
    }
  } catch (err) {
    if (DEBUG) log('xhr patch skipped', err)
  }

  /* EventSource wrapper.

     MUST use class extends: EventSource is a real DOM constructor and cannot
     be invoked via .call() — the previous prototype-shuffle wrapper made
     EVERY new EventSource(...) on the page throw
     "Failed to construct 'EventSource'" and broke all SSE consumers. */
  try {
    if (typeof window.EventSource === 'function') {
      var OriginalEventSource = window.EventSource
      class PatchedEventSource extends OriginalEventSource {
        constructor(url, config) {
          if (typeof url === 'string') url = routeUrl(url)
          super(url, config)
        }
      }
      Object.defineProperty(PatchedEventSource, 'name', { value: 'EventSource' })
      window.EventSource = PatchedEventSource
    }
  } catch (err) {
    if (DEBUG) log('eventsource patch skipped', err)
  }

  /* WebSocket transport (socket.io websocket upgrade path).

     The webserver's upgrade registry is exact-path only and cannot host
     socket.io's dynamic upgrade URLs, so the plugin runs a companion tunnel
     on its own loopback port (injected as __DSH_OVERLEAF_WS_PORT__). When
     that port is known, same-origin WebSocket targets are redirected there;
     the tunnel forwards the request verbatim to the upstream origin. */
  try {
    var OriginalWebSocket = window.WebSocket
    if (typeof OriginalWebSocket === 'function') {
      var WS_PORT = parseInt(window.__DSH_OVERLEAF_WS_PORT__, 10) || 0
      markDiagnostic('ws-port', WS_PORT)
      function PatchedWebSocket(url, protocols) {
        try {
          if (typeof url === 'string' && url.indexOf('//') === 0) {
            url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + url
          }
          if (typeof url === 'string' && url.charAt(0) === '/') {
            if (WS_PORT > 0) {
              url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + '127.0.0.1:' + WS_PORT + url
            } else {
              url = (location.protocol === 'https:' ? 'wss:' : 'ws:') + window.location.host + PREFIX + url
            }
          } else if (typeof url === 'string' && url.indexOf(window.location.host) !== -1 && !isProxyUrl(url)) {
            if (WS_PORT > 0) {
              var parts = url.split(window.location.host)
              url = parts[0] + '127.0.0.1:' + WS_PORT + parts.slice(1).join(window.location.host)
            } else {
              url = url.replace(location.protocol + '//' + window.location.host,
                location.protocol + '//' + window.location.host + PREFIX)
            }
          }
        } catch (err) {
          if (DEBUG) log('ws url fix failed', err)
        }
        var socketUrl = String(url)
        try {
          var parsedSocketUrl = new URL(socketUrl)
          markDiagnostic('ws-target', parsedSocketUrl.host)
        } catch (err) {
          markDiagnostic('ws-target', 'invalid-url')
        }
        markDiagnostic('ws-state', 'connecting')
        var socket = new OriginalWebSocket(url, protocols)
        socket.addEventListener('open', function () { markDiagnostic('ws-state', 'open') })
        socket.addEventListener('error', function () { markDiagnostic('ws-state', 'error') })
        socket.addEventListener('close', function (event) {
          markDiagnostic('ws-state', 'closed:' + String(event && event.code || 0))
        })
        return socket
      }
      Object.defineProperty(PatchedWebSocket, 'name', { value: 'WebSocket' })
      // Preserve the native constructor contract. Overleaf compares its
      // connection state against WebSocket.OPEN/CLOSED before it ever creates
      // a socket; dropping those static constants makes both sides undefined
      // and canReconnect() stays false forever. Sharing the native prototype
      // also keeps event.target instanceof WebSocket true after wrapping.
      Object.setPrototypeOf(PatchedWebSocket, OriginalWebSocket)
      PatchedWebSocket.prototype = OriginalWebSocket.prototype
      window.WebSocket = PatchedWebSocket
    }
  } catch (err) {
    if (DEBUG) log('websocket patch skipped', err)
  }

  /* navigator.sendBeacon wrapper (analytics endpoints like /event/* are
     POSTed through it and would otherwise bypass the proxy). */
  try {
    if (navigator.sendBeacon && !navigator.sendBeacon.__dshOverleafWrapped) {
      var originalSendBeacon = navigator.sendBeacon.bind(navigator)
      var wrappedSendBeacon = function (url, data) {
        try {
          if (typeof url === 'string') url = routeUrl(url)
        } catch (err) {
          if (DEBUG) log('beacon url fix failed', err)
        }
        return originalSendBeacon(url, data)
      }
      wrappedSendBeacon.__dshOverleafWrapped = true
      Object.defineProperty(navigator, 'sendBeacon', { value: wrappedSendBeacon, configurable: true })
    }
  } catch (err) {
    if (DEBUG) log('sendBeacon patch skipped', err)
  }

  /* Resource-load failure fallback (capture phase - resource errors do not
     bubble). If an IMG/SCRIPT/LINK failed on an un-prefixed root-relative
     URL that slipped past every other rewriter, rebase it in place once and
     let the browser retry. */
  try {
    document.addEventListener('error', safe(function (event) {
      try {
        var el = event.target
        if (!el || el.nodeType !== 1 || !el.getAttribute) return
        var tag = el.tagName
        var attr = tag === 'IMG' ? 'src' : tag === 'SCRIPT' ? 'src' : tag === 'LINK' ? 'href' : null
        if (attr === null) return
        var value = el.getAttribute(attr)
        if (typeof value !== 'string' || value.charAt(0) !== '/' || value.indexOf(PREFIX) === 0
          || value.indexOf('/overleaf/workbench/') === 0) return
        if (el.getAttribute('data-dsh-retried')) return
        el.setAttribute('data-dsh-retried', '1')
        el.setAttribute(attr, PREFIX + value)
      } catch (err) {}
    }, 'resource error fallback'), true)
  } catch (err) {
    if (DEBUG) log('resource fallback skipped', err)
  }

  /* ---------------------------------------------------------------- */
  /* CodeMirror / editor probes                                       */
  /* ---------------------------------------------------------------- */

  function findCm5() {
    try {
      var holders = Array.prototype.slice.call(document.querySelectorAll('.CodeMirror'))
      var instances = []
      for (var i = 0; i < holders.length; i++) {
        var inst = holders[i].CodeMirror
        if (inst) instances.push(inst)
      }
      if (instances.length === 0) return undefined
      var focused = instances.filter(function (cm) { return cm.hasFocus && cm.hasFocus() })
      if (focused.length > 0) return focused[0]
      return instances[0]
    } catch (err) {
      return undefined
    }
  }

  /* Locate the live CodeMirror 6 EditorView. @codemirror/view stores the
     view on the .cm-editor DOM node under the key "cmView", but that field
     is a ContentView wrapper - the EditorView itself sits on its "view"
     property (and may be nested one level deeper), so unwrap before
     validating. NOTE: no backticks or dollar-brace sequences are allowed
     inside this template literal (see v0.1.10 lesson). */
  function asEditorView(candidate) {
    var hop = candidate
    for (var depth = 0; hop && depth < 4; depth++) {
      try {
        if (hop.state && hop.state.doc && typeof hop.dispatch === 'function') return hop
      } catch (err) {}
      hop = hop.view
    }
    return undefined
  }

  function findCm6() {
    try {
      var roots = document.querySelectorAll('.cm-editor')
      for (var i = 0; i < roots.length; i++) {
        var holder = roots[i]
        var direct = asEditorView(holder.cmView)
          || asEditorView(holder.editor)
          || asEditorView(holder.parentNode && holder.parentNode.__codemirrorView)
        if (direct) return direct
        var inner = holder.querySelector && holder.querySelector('.cm-scroller')
        if (inner) {
          var viaInner = asEditorView(inner.cmView)
          if (viaInner) return viaInner
        }
      }
      /* Last resort: scan own properties of editor DOM nodes for an object
         shaped like an EditorView (state.doc + dispatch). */
      var nodes = document.querySelectorAll('.cm-editor, .cm-content, .cm-scroller')
      for (var n = 0; n < nodes.length; n++) {
        var keys = Object.keys(nodes[n] || {})
        for (var k = 0; k < keys.length; k++) {
          var value = null
          try { value = nodes[n][keys[k]] } catch (err) { continue }
          var found = asEditorView(value)
          if (found) return found
        }
      }
      return undefined
    } catch (err) {
      return undefined
    }
  }

  function editorKind(cm) {
    if (!cm) return 'none'
    if (typeof cm.replaceSelection === 'function') return 'cm5'
    if (cm.state && typeof cm.dispatch === 'function') return 'cm6'
    return 'unknown'
  }

  function insertViaCm5(cm, text) {
    var snapshot = String(cm.getValue())
    rememberSnapshot(snapshot)
    cm.replaceSelection(text)
    cm.focus()
    return true
  }

  function insertViaCm6(view, text) {
    var state = view.state
    var snapshot = state.doc.toString()
    rememberSnapshot(snapshot)
    var from = state.selection.main.from
    var to = state.selection.main.to
    view.dispatch({ changes: { from: from, to: to, insert: text }, selection: { anchor: from + text.length } })
    view.focus()
    return true
  }

  function insertFallback(text) {
    var active = document.activeElement
    var editable = active && (active.tagName === 'TEXTAREA' || active.isContentEditable)
    if (editable && document.execCommand) {
      document.execCommand('insertText', false, text)
      return true
    }
    var holder = document.querySelector('.ace_text-input')
    if (holder) {
      holder.focus()
      if (document.execCommand) {
        document.execCommand('insertText', false, text)
        return true
      }
    }
    return false
  }

  /* ---------------------------------------------------------------- */
  /* Snapshot buffer (rollback)                                       */
  /* ---------------------------------------------------------------- */

  var SNAPSHOT_KEY = 'dsh-overleaf:snapshot'
  function readDocValue() {
    try {
      var cm5 = findCm5()
      if (cm5) return String(cm5.getValue())
      var cm6 = findCm6()
      if (cm6) return cm6.state.doc.toString()
      return undefined
    } catch (err) {
      return undefined
    }
  }

  /* Cursor context for AI prompts: the text around the caret plus the caret
     offset, so the agent can ground its edit in the real document. */
  function readCursorContext(radius) {
    try {
      var docValue = readDocValue()
      if (docValue === undefined) return undefined
      var text = String(docValue)
      var cursor = -1
      var cm5 = findCm5()
      if (cm5) {
        try { cursor = cm5.indexFromPos(cm5.getCursor()) } catch (err) { cursor = -1 }
      } else {
        var cm6 = findCm6()
        if (cm6) {
          try { cursor = cm6.state.selection.main.head } catch (err2) { cursor = -1 }
        }
      }
      if (cursor < 0) cursor = 0
      var r = Number(radius) || 1200
      var from = Math.max(0, cursor - r)
      var to = Math.min(text.length, cursor + r)
      return {
        cursor: cursor,
        docLength: text.length,
        before: text.slice(from, cursor),
        after: text.slice(cursor, to),
      }
    } catch (err) {
      return undefined
    }
  }
  function rememberSnapshot(docValue) {
    try {
      if (docValue === undefined || docValue === null) return
      window.localStorage.setItem(SNAPSHOT_KEY, JSON.stringify({
        time: Date.now(),
        doc: docValue,
      }))
      sendToParent({ type: 'snapshot-saved' })
    } catch (err) {
      if (DEBUG) log('snapshot failed', err)
    }
  }

  /* ---------------------------------------------------------------- */
  /* Parent command handling                                          */
  /* ---------------------------------------------------------------- */

  window.addEventListener('message', safe(function (event) {
    var data = event.data
    if (!data || data.ns !== NS) return
    if (data.type === 'insert') {
      try {
        var cm5 = findCm5()
        if (cm5) {
          insertViaCm5(cm5, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm5' })
          return
        }
        var cm6 = findCm6()
        if (cm6) {
          insertViaCm6(cm6, String(data.text || ''))
          sendToParent({ type: 'insert-done', ok: true, engine: 'cm6' })
          return
        }
        var fellBack = insertFallback(String(data.text || ''))
        sendToParent({ type: 'insert-done', ok: !!fellBack, engine: fellBack ? 'fallback' : 'none',
          error: fellBack ? undefined : 'editor API not detected; paste manually from the reply' })
      } catch (err) {
        sendToParent({ type: 'insert-done', ok: false, error: err && err.message })
      }
      return
    }
    if (data.type === 'snapshot') {
      rememberSnapshot(readDocValue())
      return
    }
    if (data.type === 'selection-request') {
      emitSelection()
      return
    }
    if (data.type === 'reveal') {
      revealText(String(data.query || ''))
      return
    }
    if (data.type === 'outline-request') {
      sendOutline()
      return
    }
    if (data.type === 'cursor-context-request') {
      try {
        var cc = readCursorContext(data.radius)
        if (cc === undefined) {
          sendToParent({ type: 'cursor-context', error: 'no-editor' })
        } else {
          sendToParent({ type: 'cursor-context', cursor: cc.cursor, docLength: cc.docLength, before: cc.before, after: cc.after })
        }
      } catch (err) {
        sendToParent({ type: 'cursor-context', error: err && err.message })
      }
      return
    }
    if (data.type === 'debug') {
      DEBUG = true
      return
    }
  }, 'message handler'), false)

  /* Extract a LaTeX section/subsection outline from the live editor document. */
  function sendOutline() {
    try {
      var docValue = readDocValue()
      if (docValue === undefined) {
        sendToParent({ type: 'outline', items: [], error: 'no-editor' })
        return
      }
      /* NOTE: inside this TS template literal every backslash that must
         survive into the generated JS is doubled (\\n, \\s, \\{). A single
         \n here becomes a REAL newline in the served script and breaks it. */
      var lines = String(docValue).split('\\n')
      var items = []
      var pattern = /^(part|chapter|section|subsection|subsubsection)\\s*\\{([^}]*)\\}/
      for (var i = 0; i < lines.length; i++) {
        var match = pattern.exec(lines[i])
        if (!match) continue
        items.push({
          level: match[1],
          title: match[2].trim(),
          line: i,
          text: lines[i],
        })
        if (items.length >= 300) break
      }
      sendToParent({ type: 'outline', items: items })
    } catch (err) {
      sendToParent({ type: 'outline', items: [], error: err && err.message })
    }
  }

  /* Report whether the caret insertion works right now (toolbar health). */
  function reportCapabilities() {
    var kind = 'none'
    if (findCm5()) kind = 'cm5'
    else if (findCm6()) kind = 'cm6'
    sendToParent({ type: 'capabilities', editor: kind })
  }
  setTimeout(safe(reportCapabilities, 'cap probe'), 1200)

  /* ---------------------------------------------------------------- */
  /* Selection reporting (R5 source side)                             */
  /* ---------------------------------------------------------------- */

  var lastSelectionSentAt = 0
  function emitSelection() {
    try {
      var sel = window.getSelection()
      if (!sel || sel.rangeCount === 0 || sel.isCollapsed) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var text = sel.toString()
      if (!text.trim()) {
        sendToParent({ type: 'selection-cleared' })
        return
      }
      var now = Date.now()
      if (now - lastSelectionSentAt < 80) return
      lastSelectionSentAt = now
      var range = sel.getRangeAt(0)
      var rect = { left: 0, top: 0, right: 0, bottom: 0 }
      try {
        var box = range.getBoundingClientRect()
        rect = { left: box.left, top: box.top, right: box.right, bottom: box.bottom }
      } catch (ignoredRectError) {}
      sendToParent({ type: 'selection', text: text, rect: rect })
    } catch (err) {
      if (DEBUG) log('selection emit failed', err)
    }
  }
  document.addEventListener('selectionchange', safe(emitSelection, 'selectionchange'), true)
  document.addEventListener('keyup', safe(emitSelection, 'keyup-selection'), true)

  /* ---------------------------------------------------------------- */
  /* Reveal + flash (chip jump-back target)                           */
  /* ---------------------------------------------------------------- */

  function revealText(query) {
    try {
      if (!query) return
      var needle = query.replace(/^\\n+|\\n+$/g, '').slice(0, 200)
      if (!needle) return
      var cm5 = findCm5()
      if (cm5) {
        var doc = String(cm5.getValue())
        var index = doc.indexOf(needle)
        if (index >= 0) {
          var from = cm5.posFromIndex(index)
          var to = cm5.posFromIndex(index + Math.min(needle.length, 400))
          cm5.setSelection(from, to)
          cm5.scrollIntoView({ from: from, to: to }, 160)
          cm5.focus()
          return
        }
      }
      /* DOM-wide soft match otherwise */
      var walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false)
      while (walker.nextNode()) {
        var node = walker.currentNode
        if (node.nodeValue && node.nodeValue.indexOf(needle.slice(0, 60)) !== -1) {
          var parentEl = node.parentElement
          if (parentEl) {
            parentEl.scrollIntoView({ block: 'center', behavior: 'smooth' })
            var previousShadow = parentEl.style.boxShadow
            parentEl.style.boxShadow = '0 0 0 3px rgba(64,156,255,0.65)'
            setTimeout(function () { parentEl.style.boxShadow = previousShadow }, 1600)
            return
          }
        }
      }
    } catch (err) {
      if (DEBUG) log('reveal failed', err)
    }
  }

  /* Notify the shell whenever the embedded URL changes (toolbar breadcrumb). */
  function announceLocation() {
    sendToParent({ type: 'url-change', href: window.location.href })
  }
  announceLocation()
  window.addEventListener('popstate', safe(announceLocation, 'popstate'))

  /* ---------------------------------------------------------------- */
  /* Dynamic resource routing                                         */
  /*                                                                  */
  /* The proxy rewrites the INITIAL HTML server-side, but SPAs (TeXPage */
  /* dashboards, Overleaf loaders) insert scripts/styles/images at     */
  /* runtime with root-relative URLs; those would fall out of the      */
  /* proxy and hit the GUI shell's own fallback routes. Sweep existing */
  /* nodes once the DOM is ready, then watch every insertion/attribute */
  /* change and rebase matching URLs in place.                         */
  /* ---------------------------------------------------------------- */

  var RESOURCE_ATTRS = ['src', 'href', 'poster', 'data-src']
  function fixResourceNode(el) {
    try {
      if (!el || el.nodeType !== 1 || !el.hasAttribute) return
      for (var i = 0; i < RESOURCE_ATTRS.length; i++) {
        var attr = RESOURCE_ATTRS[i]
        if (!el.hasAttribute(attr)) continue
        var value = el.getAttribute(attr)
        if (typeof value !== 'string') continue
        /* Only single-leading-slash URLs: leaves #fragments, //host, and
           schemes untouched, and skips anything already proxied or the
           bridge script itself. */
        if (value.charAt(0) !== '/' || value.charAt(1) === '/') continue
        if (value.indexOf(PREFIX + '/') === 0 || value.indexOf('/overleaf/workbench/') === 0) continue
        el.setAttribute(attr, PREFIX + value)
      }
    } catch (err) {
      if (DEBUG) log('fixResourceNode failed', err)
    }
  }
  try {
    var resourceObserver = new MutationObserver(function (mutations) {
      for (var i = 0; i < mutations.length; i++) {
        var mutation = mutations[i]
        if (mutation.type === 'attributes') {
          fixResourceNode(mutation.target)
          continue
        }
        for (var j = 0; j < mutation.addedNodes.length; j++) {
          var added = mutation.addedNodes[j]
          fixResourceNode(added)
          if (added && added.querySelectorAll) {
            var list = added.querySelectorAll('[src],[href],[poster],[data-src]')
            for (var k = 0; k < list.length; k++) fixResourceNode(list[k])
          }
        }
      }
    })
    function startResourceObserver() {
      if (!document.documentElement) {
        setTimeout(startResourceObserver, 50)
        return
      }
      resourceObserver.observe(document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: RESOURCE_ATTRS,
      })
    }
    startResourceObserver()
  } catch (err) {
    if (DEBUG) log('resource observer unavailable', err)
  }

  document.addEventListener('DOMContentLoaded', safe(function () {
    try {
      var list = document.querySelectorAll('[src],[href],[poster],[data-src]')
      for (var i = 0; i < list.length; i++) fixResourceNode(list[i])
    } catch (err) {
      if (DEBUG) log('initial sweep failed', err)
    }
    announceLocation()
    reportCapabilities()
  }, 'dom ready'))

  log('bridge ready')
})()
`
}
